export type MessageDirectType = {
  messageId?: number;
  userId?: number;
  syncId?: number;
  senderId?: number;
  senderUsername?: string;
  senderAvatarFileId?: number;
  senderAvatarMediaType?: string;
  receiverId?: number;
  receiverUsername?: string;
  receiverAvatarFileId?: number;
  receiverAvatarMediaType?: string;
  content?: string;
  messageType?: number;
  replyMessageId?: number;
  status?: number;
  extra?: Record<string, any>;
  createTime?: string;
  updateTime?: string;
};
