import type { AnnotationDefinition } from "./types";

import { MESSAGE_TYPE } from "../messageType";

const IMAGE_MESSAGE_TYPES = [MESSAGE_TYPE.IMG] as const;
const SOUND_MESSAGE_TYPES = [MESSAGE_TYPE.SOUND] as const;
const VIDEO_MESSAGE_TYPES = [MESSAGE_TYPE.VIDEO] as const;
const TEXTUAL_MESSAGE_TYPES = [MESSAGE_TYPE.TEXT, MESSAGE_TYPE.INTRO_TEXT, MESSAGE_TYPE.DICE] as const;
const FIGURE_MESSAGE_TYPES = [MESSAGE_TYPE.TEXT, MESSAGE_TYPE.DICE] as const;
const EFFECT_MESSAGE_TYPES = [MESSAGE_TYPE.EFFECT] as const;
const CLEAR_CONTROL_MESSAGE_TYPES = [MESSAGE_TYPE.TEXT, MESSAGE_TYPE.INTRO_TEXT, MESSAGE_TYPE.DICE, MESSAGE_TYPE.EFFECT] as const;
const SCENE_CONTROL_MESSAGE_TYPES = [MESSAGE_TYPE.TEXT, MESSAGE_TYPE.DICE, MESSAGE_TYPE.IMG, MESSAGE_TYPE.EFFECT] as const;
const BACKGROUND_EXIT_MESSAGE_TYPES = [MESSAGE_TYPE.TEXT, MESSAGE_TYPE.DICE, MESSAGE_TYPE.IMG, MESSAGE_TYPE.EFFECT] as const;

export const BUILTIN_ANNOTATIONS: AnnotationDefinition[] = [
  { id: "sys:bgm", label: "BGM", category: "音频", tone: "info", source: "builtin", messageTypes: SOUND_MESSAGE_TYPES },
  { id: "sys:se", label: "音效", category: "音频", tone: "info", source: "builtin", messageTypes: SOUND_MESSAGE_TYPES },

  { id: "sys:cg", label: "CG", category: "图片", tone: "primary", source: "builtin", messageTypes: IMAGE_MESSAGE_TYPES },
  { id: "sys:bg", label: "背景", category: "图片", tone: "primary", source: "builtin", messageTypes: IMAGE_MESSAGE_TYPES },
  { id: "image.show", label: "展示", category: "图片", tone: "primary", source: "builtin", messageTypes: IMAGE_MESSAGE_TYPES },
  { id: "background.anim.enter", label: "淡入", category: "背景进场", tone: "primary", source: "builtin", messageTypes: IMAGE_MESSAGE_TYPES },
  { id: "background.anim.enter-from-left", label: "从左", category: "背景进场", tone: "primary", source: "builtin", messageTypes: IMAGE_MESSAGE_TYPES },
  { id: "background.anim.enter-from-right", label: "从右", category: "背景进场", tone: "primary", source: "builtin", messageTypes: IMAGE_MESSAGE_TYPES },
  { id: "background.anim.blur-in", label: "模糊", category: "背景进场", tone: "primary", source: "builtin", messageTypes: IMAGE_MESSAGE_TYPES },
  { id: "background.anim.exit", label: "淡出", category: "背景出场", tone: "primary", source: "builtin", messageTypes: BACKGROUND_EXIT_MESSAGE_TYPES },
  { id: "background.anim.exit-to-left", label: "向左", category: "背景出场", tone: "primary", source: "builtin", messageTypes: BACKGROUND_EXIT_MESSAGE_TYPES },
  { id: "background.anim.exit-to-right", label: "向右", category: "背景出场", tone: "primary", source: "builtin", messageTypes: BACKGROUND_EXIT_MESSAGE_TYPES },
  { id: "background.speed.fast", label: "快", category: "背景速度", tone: "info", source: "builtin", messageTypes: BACKGROUND_EXIT_MESSAGE_TYPES },
  { id: "background.speed.normal", label: "标准", category: "背景速度", tone: "info", source: "builtin", messageTypes: BACKGROUND_EXIT_MESSAGE_TYPES },
  { id: "background.speed.slow", label: "慢", category: "背景速度", tone: "info", source: "builtin", messageTypes: BACKGROUND_EXIT_MESSAGE_TYPES },

  { id: "effect.en_hmm.webp", label: "en_hmm", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_hmm.webp", hideLabel: true, effectFrames: 36, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_doubt.webp", label: "en_doubt", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_doubt.webp", hideLabel: true, effectFrames: 22, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_answer.webp", label: "en_answer", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_answer.webp", hideLabel: true, effectFrames: 26, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_sad.webp", label: "en_sad", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_sad.webp", hideLabel: true, effectFrames: 42, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_sweat.webp", label: "en_sweat", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_sweat.webp", hideLabel: true, effectFrames: 33, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_shiny.webp", label: "en_shiny", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_shiny.webp", hideLabel: true, effectFrames: 54, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_upset.webp", label: "en_upset", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_upset.webp", hideLabel: true, effectFrames: 47, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_shy.webp", label: "en_shy", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_shy.webp", hideLabel: true, effectFrames: 33, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_suki.webp", label: "en_suki", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_suki.webp", hideLabel: true, effectFrames: 34, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_warning.webp", label: "en_warning", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_warning.webp", hideLabel: true, effectFrames: 38, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_omit.webp", label: "en_omit", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_omit.webp", hideLabel: true, effectFrames: 26, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_chat.webp", label: "en_chat", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_chat.webp", hideLabel: true, effectFrames: 35, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_getit.webp", label: "en_getit", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_getit.webp", hideLabel: true, effectFrames: 20, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "effect.en_angry.webp", label: "en_angry", category: "特效", tone: "accent", source: "builtin", iconUrl: "/annotations/effects/en_angry.webp", hideLabel: true, effectFrames: 26, showInNormalMode: true, messageTypes: TEXTUAL_MESSAGE_TYPES },

  { id: "figure.mini-avatar", label: "小头像", category: "立绘", tone: "accent", source: "builtin", messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.pos.left", label: "左", category: "立绘位置", tone: "accent", source: "builtin", messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "figure.pos.left-center", label: "左中", category: "立绘位置", tone: "accent", source: "builtin", messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "figure.pos.center", label: "中", category: "立绘位置", tone: "accent", source: "builtin", messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "figure.pos.right-center", label: "右中", category: "立绘位置", tone: "accent", source: "builtin", messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "figure.pos.right", label: "右", category: "立绘位置", tone: "accent", source: "builtin", messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "figure.anim.enter", label: "淡入", category: "进场动画", tone: "accent", source: "builtin", messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-enter-from-left", label: "从左入场", category: "进场动画", tone: "accent", source: "builtin", messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-enter-from-right", label: "从右入场", category: "进场动画", tone: "accent", source: "builtin", messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-down", label: "下落", category: "动作", tone: "accent", source: "builtin", showInNormalMode: true, messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-left-falldown", label: "左倒", category: "动作", tone: "accent", source: "builtin", showInNormalMode: true, messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-right-falldown", label: "右倒", category: "动作", tone: "accent", source: "builtin", showInNormalMode: true, messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-jump-twice", label: "二连跳", category: "动作", tone: "accent", source: "builtin", showInNormalMode: true, messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-jump", label: "跳跃", category: "动作", tone: "accent", source: "builtin", showInNormalMode: true, messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-shake", label: "摇晃", category: "动作", tone: "accent", source: "builtin", showInNormalMode: true, messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-bigshake", label: "大摇晃", category: "动作", tone: "accent", source: "builtin", showInNormalMode: true, messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.exit", label: "淡出", category: "出场动画", tone: "accent", source: "builtin", messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-exit-to-left", label: "从左退场", category: "出场动画", tone: "accent", source: "builtin", messageTypes: FIGURE_MESSAGE_TYPES },
  { id: "figure.anim.ba-exit-to-right", label: "从右退场", category: "出场动画", tone: "accent", source: "builtin", messageTypes: FIGURE_MESSAGE_TYPES },

  { id: "dialog.notend", label: "自动续播下句", category: "控制", tone: "neutral", source: "builtin", messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "dialog.concat", label: "续接上文", category: "控制", tone: "neutral", source: "builtin", messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "dialog.next", label: "立即执行后续", category: "控制", tone: "neutral", source: "builtin", messageTypes: TEXTUAL_MESSAGE_TYPES },
  { id: "video.skipoff", label: "禁止跳过", category: "控制", tone: "warning", source: "builtin", messageTypes: VIDEO_MESSAGE_TYPES },
  { id: "scene.textbox.hide", label: "隐藏", category: "场景文本框", tone: "info", source: "builtin", messageTypes: SCENE_CONTROL_MESSAGE_TYPES },
  { id: "scene.textbox.show", label: "显示", category: "场景文本框", tone: "info", source: "builtin", messageTypes: SCENE_CONTROL_MESSAGE_TYPES },
  { id: "scene.film.on", label: "开启", category: "场景电影", tone: "info", source: "builtin", messageTypes: SCENE_CONTROL_MESSAGE_TYPES },
  { id: "scene.film.off", label: "关闭", category: "场景电影", tone: "info", source: "builtin", messageTypes: SCENE_CONTROL_MESSAGE_TYPES },
  { id: "scene.effect.rain", label: "下雨", category: "控制", tone: "info", source: "builtin", messageTypes: EFFECT_MESSAGE_TYPES },
  { id: "scene.effect.snow", label: "下雪", category: "控制", tone: "info", source: "builtin", messageTypes: EFFECT_MESSAGE_TYPES },
  { id: "scene.effect.sakura", label: "樱花", category: "控制", tone: "info", source: "builtin", messageTypes: EFFECT_MESSAGE_TYPES },
  { id: "scene.effect.stop", label: "停止特效", category: "控制", tone: "warning", source: "builtin", messageTypes: EFFECT_MESSAGE_TYPES },
  { id: "image.clear", label: "清除展示图", category: "控制", tone: "warning", source: "builtin", messageTypes: CLEAR_CONTROL_MESSAGE_TYPES },
  { id: "background.clear", label: "清除背景", category: "控制", tone: "warning", source: "builtin", messageTypes: CLEAR_CONTROL_MESSAGE_TYPES },
  { id: "bgm.clear", label: "清除BGM", category: "控制", tone: "warning", source: "builtin", messageTypes: CLEAR_CONTROL_MESSAGE_TYPES },
  { id: "figure.clear", label: "清除立绘", category: "控制", tone: "warning", source: "builtin", messageTypes: CLEAR_CONTROL_MESSAGE_TYPES },
];

export const NORMAL_MODE_HIDDEN_ANNOTATION_IDS = new Set([
  "sys:bgm",
  "sys:se",
  "sys:cg",
  "sys:bg",
  "image.show",
  "background.anim.enter",
  "background.anim.enter-from-left",
  "background.anim.enter-from-right",
  "background.anim.blur-in",
  "background.anim.exit",
  "background.anim.exit-to-left",
  "background.anim.exit-to-right",
  "background.speed.fast",
  "background.speed.normal",
  "background.speed.slow",
  "figure.mini-avatar",
  "figure.anim.ba-exit-to-left",
  "figure.anim.ba-enter-from-left",
  "figure.anim.enter",
  "figure.anim.exit",
  "figure.anim.ba-enter-from-right",
  "figure.anim.ba-exit-to-right",
  "figure.pos.left",
  "figure.pos.left-center",
  "figure.pos.center",
  "figure.pos.right-center",
  "figure.pos.right",
  "dialog.notend",
  "dialog.concat",
  "dialog.next",
  "video.skipoff",
  "scene.textbox.hide",
  "scene.textbox.show",
  "scene.film.on",
  "scene.film.off",
  "scene.effect.rain",
  "scene.effect.snow",
  "scene.effect.sakura",
  "scene.effect.stop",
  "image.clear",
  "background.clear",
  "bgm.clear",
  "figure.clear",
]);
