directories:
  output: ./buileder
  buildResources: build
productName: 团剧共创
files:
  - filter:
      - ./electron/main.cjs
      - ./build
extraFiles:
  - filter:
      - ./videos
      - ./cvideo
electronVersion: 35.0.3
