// 属性名别名表保持独立，避免只做表达式计算时加载完整骰子命令执行器。

// noinspection NonAsciiCharacters
export const COC_ABILITY_ALIASES: Record<string, string> = {
  str: "力量",
  dex: "敏捷",
  pow: "意志",
  con: "体质",
  app: "外貌",
  edu: "教育",
  siz: "体型",
  int: "智力",
  灵感: "智力",
  san: "san",
  理智: "san",
  理智值: "san",
  san值: "san",
  luck: "幸运",
  运气: "幸运",
  mp: "mp",
  魔法: "mp",
  魔法值: "mp",
  魔法值上限: "mpm",
  mpmax: "mpm",
  体力: "hp",
  hp: "hp",
  体力值: "hp",
  生命值: "hp",
  最大生命值: "hpm",
  hpmax: "hpm",
  理智值上限: "sanm",
  理智上限: "sanm",
  sanmax: "sanm",
  cm: "克苏鲁神话",
  克苏鲁: "克苏鲁神话",
  信誉: "信用评级",
  信用: "信用评级",
  计算机: "计算机使用",
  电脑: "计算机使用",
  驾驶: "汽车驾驶",
  汽车: "汽车驾驶",
  图书馆: "图书馆使用",
  开锁: "锁匠",
  撬锁: "锁匠",
  领航: "导航",
  重型操作: "操作重型机械",
  重型机械: "操作重型机械",
  重型: "操作重型机械",
  侦察: "侦查",
};

// noinspection NonAsciiCharacters
export const FU_PROPERTY_ALIASES: Record<string, string> = {
  灵巧度: "敏捷",
  dex: "敏捷",
  灵巧: "敏捷",
  敏捷: "敏捷",
  敏捷值: "敏捷",
  洞察力: "洞察",
  ins: "洞察",
  洞察: "洞察",
  洞察值: "洞察",
  感知: "洞察",
  感知值: "洞察",
  力量值: "力量",
  mig: "力量",
  力量: "力量",
  意志力: "意志",
  wlp: "意志",
  意志: "意志",
  意志值: "意志",
};

export function createRoleAbilityAliasMapSet(): { [key: string]: Map<string, string> } {
  return {
    1: new Map<string, string>(Object.entries(COC_ABILITY_ALIASES)),
    2: new Map<string, string>(),
    3: new Map<string, string>(Object.entries(FU_PROPERTY_ALIASES)),
    7: new Map<string, string>(),
  };
}
