/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScrollSequenceMotionDemoRouteImport } from './routes/scroll-sequence-motion-demo'
import { Route as ScrollSequenceDemoRouteImport } from './routes/scroll-sequence-demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as InviteCodeRouteImport } from './routes/invite/$code'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardResourceRouteImport } from './routes/_dashboard/resource'
import { Route as DashboardNotificationsRouteImport } from './routes/_dashboard/notifications'
import { Route as DashboardCollectionRouteImport } from './routes/_dashboard/collection'
import { Route as DashboardAiImageRouteImport } from './routes/_dashboard/ai-image'
import { Route as DashboardActivitiesRouteImport } from './routes/_dashboard/activities'
import { Route as DashboardRoleRouteRouteImport } from './routes/_dashboard/role/route'
import { Route as DashboardMaterialRouteRouteImport } from './routes/_dashboard/material/route'
import { Route as DashboardRoleIndexRouteImport } from './routes/_dashboard/role/index'
import { Route as DashboardRepositoryIndexRouteImport } from './routes/_dashboard/repository/index'
import { Route as DashboardFeedbackIndexRouteImport } from './routes/_dashboard/feedback/index'
import { Route as RoomMapSpaceIdRoomIdRouteImport } from './routes/room-map/$spaceId/$roomId'
import { Route as DashboardRoleChar123RoleIdChar125RouteImport } from './routes/_dashboard/role/{-$roleId}'
import { Route as DashboardRepositoryCreateRouteImport } from './routes/_dashboard/repository/create'
import { Route as DashboardRepositoryCommitChainRouteImport } from './routes/_dashboard/repository/commit-chain'
import { Route as DashboardFeedbackIssueIdRouteImport } from './routes/_dashboard/feedback/$issueId'
import { Route as DashboardProfileUserIdRouteRouteImport } from './routes/_dashboard/profile/$userId/route'
import { Route as DashboardChatChatLayoutRouteRouteImport } from './routes/_dashboard/chat/_chat-layout/route'
import { Route as DashboardProfileUserIdIndexRouteImport } from './routes/_dashboard/profile/$userId/index'
import { Route as DashboardChatDiscoverIndexRouteImport } from './routes/_dashboard/chat/discover/index'
import { Route as DashboardChatChatLayoutIndexRouteImport } from './routes/_dashboard/chat/_chat-layout/index'
import { Route as DashboardRepositoryDetailChar123IdChar125RouteImport } from './routes/_dashboard/repository/detail/{-$id}'
import { Route as DashboardProfileUserIdWorksRouteImport } from './routes/_dashboard/profile/$userId/works'
import { Route as DashboardProfileUserIdActivitiesRouteImport } from './routes/_dashboard/profile/$userId/activities'
import { Route as DashboardMaterialSpaceSpaceIdRouteImport } from './routes/_dashboard/material/space/$spaceId'
import { Route as DashboardDocSpaceIdDocIdRouteImport } from './routes/_dashboard/doc/$spaceId/$docId'
import { Route as DashboardChatDiscoverMyRouteImport } from './routes/_dashboard/chat/discover/my'
import { Route as DashboardChatDiscoverMaterialIndexRouteImport } from './routes/_dashboard/chat/discover/material/index'
import { Route as DashboardChatDiscoverMaterialMyRouteImport } from './routes/_dashboard/chat/discover/material/my'
import { Route as DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125RouteImport } from './routes/_dashboard/chat/_chat-layout/$spaceId.{-$roomId}.{-$messageId}'
import { Route as DashboardChatChatLayoutSpaceIdDocDocIdRouteImport } from './routes/_dashboard/chat/_chat-layout/$spaceId.doc.$docId'
import { Route as DashboardChatChatLayoutSpaceIdRoomIdSettingRouteImport } from './routes/_dashboard/chat/_chat-layout/$spaceId.$roomId.setting'

const ScrollSequenceMotionDemoRoute =
  ScrollSequenceMotionDemoRouteImport.update({
    id: '/scroll-sequence-motion-demo',
    path: '/scroll-sequence-motion-demo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScrollSequenceDemoRoute = ScrollSequenceDemoRouteImport.update({
  id: '/scroll-sequence-demo',
  path: '/scroll-sequence-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardResourceRoute = DashboardResourceRouteImport.update({
  id: '/resource',
  path: '/resource',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCollectionRoute = DashboardCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAiImageRoute = DashboardAiImageRouteImport.update({
  id: '/ai-image',
  path: '/ai-image',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardActivitiesRoute = DashboardActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRoleRouteRoute = DashboardRoleRouteRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMaterialRouteRoute = DashboardMaterialRouteRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRoleIndexRoute = DashboardRoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoleRouteRoute,
} as any)
const DashboardRepositoryIndexRoute =
  DashboardRepositoryIndexRouteImport.update({
    id: '/repository/',
    path: '/repository/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFeedbackIndexRoute = DashboardFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const RoomMapSpaceIdRoomIdRoute = RoomMapSpaceIdRoomIdRouteImport.update({
  id: '/room-map/$spaceId/$roomId',
  path: '/room-map/$spaceId/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleChar123RoleIdChar125Route =
  DashboardRoleChar123RoleIdChar125RouteImport.update({
    id: '/{-$roleId}',
    path: '/{-$roleId}',
    getParentRoute: () => DashboardRoleRouteRoute,
  } as any)
const DashboardRepositoryCreateRoute =
  DashboardRepositoryCreateRouteImport.update({
    id: '/repository/create',
    path: '/repository/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRepositoryCommitChainRoute =
  DashboardRepositoryCommitChainRouteImport.update({
    id: '/repository/commit-chain',
    path: '/repository/commit-chain',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFeedbackIssueIdRoute =
  DashboardFeedbackIssueIdRouteImport.update({
    id: '/feedback/$issueId',
    path: '/feedback/$issueId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProfileUserIdRouteRoute =
  DashboardProfileUserIdRouteRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChatChatLayoutRouteRoute =
  DashboardChatChatLayoutRouteRouteImport.update({
    id: '/chat/_chat-layout',
    path: '/chat',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProfileUserIdIndexRoute =
  DashboardProfileUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProfileUserIdRouteRoute,
  } as any)
const DashboardChatDiscoverIndexRoute =
  DashboardChatDiscoverIndexRouteImport.update({
    id: '/chat/discover/',
    path: '/chat/discover/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChatChatLayoutIndexRoute =
  DashboardChatChatLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardChatChatLayoutRouteRoute,
  } as any)
const DashboardRepositoryDetailChar123IdChar125Route =
  DashboardRepositoryDetailChar123IdChar125RouteImport.update({
    id: '/repository/detail/{-$id}',
    path: '/repository/detail/{-$id}',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProfileUserIdWorksRoute =
  DashboardProfileUserIdWorksRouteImport.update({
    id: '/works',
    path: '/works',
    getParentRoute: () => DashboardProfileUserIdRouteRoute,
  } as any)
const DashboardProfileUserIdActivitiesRoute =
  DashboardProfileUserIdActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => DashboardProfileUserIdRouteRoute,
  } as any)
const DashboardMaterialSpaceSpaceIdRoute =
  DashboardMaterialSpaceSpaceIdRouteImport.update({
    id: '/space/$spaceId',
    path: '/space/$spaceId',
    getParentRoute: () => DashboardMaterialRouteRoute,
  } as any)
const DashboardDocSpaceIdDocIdRoute =
  DashboardDocSpaceIdDocIdRouteImport.update({
    id: '/doc/$spaceId/$docId',
    path: '/doc/$spaceId/$docId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChatDiscoverMyRoute = DashboardChatDiscoverMyRouteImport.update({
  id: '/chat/discover/my',
  path: '/chat/discover/my',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChatDiscoverMaterialIndexRoute =
  DashboardChatDiscoverMaterialIndexRouteImport.update({
    id: '/chat/discover/material/',
    path: '/chat/discover/material/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChatDiscoverMaterialMyRoute =
  DashboardChatDiscoverMaterialMyRouteImport.update({
    id: '/chat/discover/material/my',
    path: '/chat/discover/material/my',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125Route =
  DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125RouteImport.update(
    {
      id: '/$spaceId/{-$roomId}/{-$messageId}',
      path: '/$spaceId/{-$roomId}/{-$messageId}',
      getParentRoute: () => DashboardChatChatLayoutRouteRoute,
    } as any,
  )
const DashboardChatChatLayoutSpaceIdDocDocIdRoute =
  DashboardChatChatLayoutSpaceIdDocDocIdRouteImport.update({
    id: '/$spaceId/doc/$docId',
    path: '/$spaceId/doc/$docId',
    getParentRoute: () => DashboardChatChatLayoutRouteRoute,
  } as any)
const DashboardChatChatLayoutSpaceIdRoomIdSettingRoute =
  DashboardChatChatLayoutSpaceIdRoomIdSettingRouteImport.update({
    id: '/$spaceId/$roomId/setting',
    path: '/$spaceId/$roomId/setting',
    getParentRoute: () => DashboardChatChatLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/scroll-sequence-demo': typeof ScrollSequenceDemoRoute
  '/scroll-sequence-motion-demo': typeof ScrollSequenceMotionDemoRoute
  '/material': typeof DashboardMaterialRouteRouteWithChildren
  '/role': typeof DashboardRoleRouteRouteWithChildren
  '/activities': typeof DashboardActivitiesRoute
  '/ai-image': typeof DashboardAiImageRoute
  '/collection': typeof DashboardCollectionRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/resource': typeof DashboardResourceRoute
  '/settings': typeof DashboardSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/chat': typeof DashboardChatChatLayoutRouteRouteWithChildren
  '/profile/$userId': typeof DashboardProfileUserIdRouteRouteWithChildren
  '/feedback/$issueId': typeof DashboardFeedbackIssueIdRoute
  '/repository/commit-chain': typeof DashboardRepositoryCommitChainRoute
  '/repository/create': typeof DashboardRepositoryCreateRoute
  '/role/{-$roleId}': typeof DashboardRoleChar123RoleIdChar125Route
  '/room-map/$spaceId/$roomId': typeof RoomMapSpaceIdRoomIdRoute
  '/feedback/': typeof DashboardFeedbackIndexRoute
  '/repository/': typeof DashboardRepositoryIndexRoute
  '/role/': typeof DashboardRoleIndexRoute
  '/chat/discover/my': typeof DashboardChatDiscoverMyRoute
  '/doc/$spaceId/$docId': typeof DashboardDocSpaceIdDocIdRoute
  '/material/space/$spaceId': typeof DashboardMaterialSpaceSpaceIdRoute
  '/profile/$userId/activities': typeof DashboardProfileUserIdActivitiesRoute
  '/profile/$userId/works': typeof DashboardProfileUserIdWorksRoute
  '/repository/detail/{-$id}': typeof DashboardRepositoryDetailChar123IdChar125Route
  '/chat/': typeof DashboardChatChatLayoutIndexRoute
  '/chat/discover/': typeof DashboardChatDiscoverIndexRoute
  '/profile/$userId/': typeof DashboardProfileUserIdIndexRoute
  '/chat/discover/material/my': typeof DashboardChatDiscoverMaterialMyRoute
  '/chat/discover/material/': typeof DashboardChatDiscoverMaterialIndexRoute
  '/chat/$spaceId/$roomId/setting': typeof DashboardChatChatLayoutSpaceIdRoomIdSettingRoute
  '/chat/$spaceId/doc/$docId': typeof DashboardChatChatLayoutSpaceIdDocDocIdRoute
  '/chat/$spaceId/{-$roomId}/{-$messageId}': typeof DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125Route
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/scroll-sequence-demo': typeof ScrollSequenceDemoRoute
  '/scroll-sequence-motion-demo': typeof ScrollSequenceMotionDemoRoute
  '/material': typeof DashboardMaterialRouteRouteWithChildren
  '/activities': typeof DashboardActivitiesRoute
  '/ai-image': typeof DashboardAiImageRoute
  '/collection': typeof DashboardCollectionRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/resource': typeof DashboardResourceRoute
  '/settings': typeof DashboardSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/': typeof DashboardIndexRoute
  '/feedback/$issueId': typeof DashboardFeedbackIssueIdRoute
  '/repository/commit-chain': typeof DashboardRepositoryCommitChainRoute
  '/repository/create': typeof DashboardRepositoryCreateRoute
  '/role/{-$roleId}': typeof DashboardRoleChar123RoleIdChar125Route
  '/room-map/$spaceId/$roomId': typeof RoomMapSpaceIdRoomIdRoute
  '/feedback': typeof DashboardFeedbackIndexRoute
  '/repository': typeof DashboardRepositoryIndexRoute
  '/role': typeof DashboardRoleIndexRoute
  '/chat/discover/my': typeof DashboardChatDiscoverMyRoute
  '/doc/$spaceId/$docId': typeof DashboardDocSpaceIdDocIdRoute
  '/material/space/$spaceId': typeof DashboardMaterialSpaceSpaceIdRoute
  '/profile/$userId/activities': typeof DashboardProfileUserIdActivitiesRoute
  '/profile/$userId/works': typeof DashboardProfileUserIdWorksRoute
  '/repository/detail/{-$id}': typeof DashboardRepositoryDetailChar123IdChar125Route
  '/chat': typeof DashboardChatChatLayoutIndexRoute
  '/chat/discover': typeof DashboardChatDiscoverIndexRoute
  '/profile/$userId': typeof DashboardProfileUserIdIndexRoute
  '/chat/discover/material/my': typeof DashboardChatDiscoverMaterialMyRoute
  '/chat/discover/material': typeof DashboardChatDiscoverMaterialIndexRoute
  '/chat/$spaceId/$roomId/setting': typeof DashboardChatChatLayoutSpaceIdRoomIdSettingRoute
  '/chat/$spaceId/doc/$docId': typeof DashboardChatChatLayoutSpaceIdDocDocIdRoute
  '/chat/$spaceId/{-$roomId}/{-$messageId}': typeof DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/scroll-sequence-demo': typeof ScrollSequenceDemoRoute
  '/scroll-sequence-motion-demo': typeof ScrollSequenceMotionDemoRoute
  '/_dashboard/material': typeof DashboardMaterialRouteRouteWithChildren
  '/_dashboard/role': typeof DashboardRoleRouteRouteWithChildren
  '/_dashboard/activities': typeof DashboardActivitiesRoute
  '/_dashboard/ai-image': typeof DashboardAiImageRoute
  '/_dashboard/collection': typeof DashboardCollectionRoute
  '/_dashboard/notifications': typeof DashboardNotificationsRoute
  '/_dashboard/resource': typeof DashboardResourceRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/chat/_chat-layout': typeof DashboardChatChatLayoutRouteRouteWithChildren
  '/_dashboard/profile/$userId': typeof DashboardProfileUserIdRouteRouteWithChildren
  '/_dashboard/feedback/$issueId': typeof DashboardFeedbackIssueIdRoute
  '/_dashboard/repository/commit-chain': typeof DashboardRepositoryCommitChainRoute
  '/_dashboard/repository/create': typeof DashboardRepositoryCreateRoute
  '/_dashboard/role/{-$roleId}': typeof DashboardRoleChar123RoleIdChar125Route
  '/room-map/$spaceId/$roomId': typeof RoomMapSpaceIdRoomIdRoute
  '/_dashboard/feedback/': typeof DashboardFeedbackIndexRoute
  '/_dashboard/repository/': typeof DashboardRepositoryIndexRoute
  '/_dashboard/role/': typeof DashboardRoleIndexRoute
  '/_dashboard/chat/discover/my': typeof DashboardChatDiscoverMyRoute
  '/_dashboard/doc/$spaceId/$docId': typeof DashboardDocSpaceIdDocIdRoute
  '/_dashboard/material/space/$spaceId': typeof DashboardMaterialSpaceSpaceIdRoute
  '/_dashboard/profile/$userId/activities': typeof DashboardProfileUserIdActivitiesRoute
  '/_dashboard/profile/$userId/works': typeof DashboardProfileUserIdWorksRoute
  '/_dashboard/repository/detail/{-$id}': typeof DashboardRepositoryDetailChar123IdChar125Route
  '/_dashboard/chat/_chat-layout/': typeof DashboardChatChatLayoutIndexRoute
  '/_dashboard/chat/discover/': typeof DashboardChatDiscoverIndexRoute
  '/_dashboard/profile/$userId/': typeof DashboardProfileUserIdIndexRoute
  '/_dashboard/chat/discover/material/my': typeof DashboardChatDiscoverMaterialMyRoute
  '/_dashboard/chat/discover/material/': typeof DashboardChatDiscoverMaterialIndexRoute
  '/_dashboard/chat/_chat-layout/$spaceId/$roomId/setting': typeof DashboardChatChatLayoutSpaceIdRoomIdSettingRoute
  '/_dashboard/chat/_chat-layout/$spaceId/doc/$docId': typeof DashboardChatChatLayoutSpaceIdDocDocIdRoute
  '/_dashboard/chat/_chat-layout/$spaceId/{-$roomId}/{-$messageId}': typeof DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/scroll-sequence-demo'
    | '/scroll-sequence-motion-demo'
    | '/material'
    | '/role'
    | '/activities'
    | '/ai-image'
    | '/collection'
    | '/notifications'
    | '/resource'
    | '/settings'
    | '/invite/$code'
    | '/chat'
    | '/profile/$userId'
    | '/feedback/$issueId'
    | '/repository/commit-chain'
    | '/repository/create'
    | '/role/{-$roleId}'
    | '/room-map/$spaceId/$roomId'
    | '/feedback/'
    | '/repository/'
    | '/role/'
    | '/chat/discover/my'
    | '/doc/$spaceId/$docId'
    | '/material/space/$spaceId'
    | '/profile/$userId/activities'
    | '/profile/$userId/works'
    | '/repository/detail/{-$id}'
    | '/chat/'
    | '/chat/discover/'
    | '/profile/$userId/'
    | '/chat/discover/material/my'
    | '/chat/discover/material/'
    | '/chat/$spaceId/$roomId/setting'
    | '/chat/$spaceId/doc/$docId'
    | '/chat/$spaceId/{-$roomId}/{-$messageId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/scroll-sequence-demo'
    | '/scroll-sequence-motion-demo'
    | '/material'
    | '/activities'
    | '/ai-image'
    | '/collection'
    | '/notifications'
    | '/resource'
    | '/settings'
    | '/invite/$code'
    | '/'
    | '/feedback/$issueId'
    | '/repository/commit-chain'
    | '/repository/create'
    | '/role/{-$roleId}'
    | '/room-map/$spaceId/$roomId'
    | '/feedback'
    | '/repository'
    | '/role'
    | '/chat/discover/my'
    | '/doc/$spaceId/$docId'
    | '/material/space/$spaceId'
    | '/profile/$userId/activities'
    | '/profile/$userId/works'
    | '/repository/detail/{-$id}'
    | '/chat'
    | '/chat/discover'
    | '/profile/$userId'
    | '/chat/discover/material/my'
    | '/chat/discover/material'
    | '/chat/$spaceId/$roomId/setting'
    | '/chat/$spaceId/doc/$docId'
    | '/chat/$spaceId/{-$roomId}/{-$messageId}'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/scroll-sequence-demo'
    | '/scroll-sequence-motion-demo'
    | '/_dashboard/material'
    | '/_dashboard/role'
    | '/_dashboard/activities'
    | '/_dashboard/ai-image'
    | '/_dashboard/collection'
    | '/_dashboard/notifications'
    | '/_dashboard/resource'
    | '/_dashboard/settings'
    | '/invite/$code'
    | '/_dashboard/'
    | '/_dashboard/chat/_chat-layout'
    | '/_dashboard/profile/$userId'
    | '/_dashboard/feedback/$issueId'
    | '/_dashboard/repository/commit-chain'
    | '/_dashboard/repository/create'
    | '/_dashboard/role/{-$roleId}'
    | '/room-map/$spaceId/$roomId'
    | '/_dashboard/feedback/'
    | '/_dashboard/repository/'
    | '/_dashboard/role/'
    | '/_dashboard/chat/discover/my'
    | '/_dashboard/doc/$spaceId/$docId'
    | '/_dashboard/material/space/$spaceId'
    | '/_dashboard/profile/$userId/activities'
    | '/_dashboard/profile/$userId/works'
    | '/_dashboard/repository/detail/{-$id}'
    | '/_dashboard/chat/_chat-layout/'
    | '/_dashboard/chat/discover/'
    | '/_dashboard/profile/$userId/'
    | '/_dashboard/chat/discover/material/my'
    | '/_dashboard/chat/discover/material/'
    | '/_dashboard/chat/_chat-layout/$spaceId/$roomId/setting'
    | '/_dashboard/chat/_chat-layout/$spaceId/doc/$docId'
    | '/_dashboard/chat/_chat-layout/$spaceId/{-$roomId}/{-$messageId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ScrollSequenceDemoRoute: typeof ScrollSequenceDemoRoute
  ScrollSequenceMotionDemoRoute: typeof ScrollSequenceMotionDemoRoute
  InviteCodeRoute: typeof InviteCodeRoute
  RoomMapSpaceIdRoomIdRoute: typeof RoomMapSpaceIdRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scroll-sequence-motion-demo': {
      id: '/scroll-sequence-motion-demo'
      path: '/scroll-sequence-motion-demo'
      fullPath: '/scroll-sequence-motion-demo'
      preLoaderRoute: typeof ScrollSequenceMotionDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll-sequence-demo': {
      id: '/scroll-sequence-demo'
      path: '/scroll-sequence-demo'
      fullPath: '/scroll-sequence-demo'
      preLoaderRoute: typeof ScrollSequenceDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/resource': {
      id: '/_dashboard/resource'
      path: '/resource'
      fullPath: '/resource'
      preLoaderRoute: typeof DashboardResourceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/notifications': {
      id: '/_dashboard/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/collection': {
      id: '/_dashboard/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof DashboardCollectionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/ai-image': {
      id: '/_dashboard/ai-image'
      path: '/ai-image'
      fullPath: '/ai-image'
      preLoaderRoute: typeof DashboardAiImageRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/activities': {
      id: '/_dashboard/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof DashboardActivitiesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/role': {
      id: '/_dashboard/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof DashboardRoleRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/material': {
      id: '/_dashboard/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof DashboardMaterialRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/role/': {
      id: '/_dashboard/role/'
      path: '/'
      fullPath: '/role/'
      preLoaderRoute: typeof DashboardRoleIndexRouteImport
      parentRoute: typeof DashboardRoleRouteRoute
    }
    '/_dashboard/repository/': {
      id: '/_dashboard/repository/'
      path: '/repository'
      fullPath: '/repository/'
      preLoaderRoute: typeof DashboardRepositoryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/feedback/': {
      id: '/_dashboard/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof DashboardFeedbackIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/room-map/$spaceId/$roomId': {
      id: '/room-map/$spaceId/$roomId'
      path: '/room-map/$spaceId/$roomId'
      fullPath: '/room-map/$spaceId/$roomId'
      preLoaderRoute: typeof RoomMapSpaceIdRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/role/{-$roleId}': {
      id: '/_dashboard/role/{-$roleId}'
      path: '/{-$roleId}'
      fullPath: '/role/{-$roleId}'
      preLoaderRoute: typeof DashboardRoleChar123RoleIdChar125RouteImport
      parentRoute: typeof DashboardRoleRouteRoute
    }
    '/_dashboard/repository/create': {
      id: '/_dashboard/repository/create'
      path: '/repository/create'
      fullPath: '/repository/create'
      preLoaderRoute: typeof DashboardRepositoryCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/repository/commit-chain': {
      id: '/_dashboard/repository/commit-chain'
      path: '/repository/commit-chain'
      fullPath: '/repository/commit-chain'
      preLoaderRoute: typeof DashboardRepositoryCommitChainRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/feedback/$issueId': {
      id: '/_dashboard/feedback/$issueId'
      path: '/feedback/$issueId'
      fullPath: '/feedback/$issueId'
      preLoaderRoute: typeof DashboardFeedbackIssueIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile/$userId': {
      id: '/_dashboard/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof DashboardProfileUserIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/chat/_chat-layout': {
      id: '/_dashboard/chat/_chat-layout'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof DashboardChatChatLayoutRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile/$userId/': {
      id: '/_dashboard/profile/$userId/'
      path: '/'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof DashboardProfileUserIdIndexRouteImport
      parentRoute: typeof DashboardProfileUserIdRouteRoute
    }
    '/_dashboard/chat/discover/': {
      id: '/_dashboard/chat/discover/'
      path: '/chat/discover'
      fullPath: '/chat/discover/'
      preLoaderRoute: typeof DashboardChatDiscoverIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/chat/_chat-layout/': {
      id: '/_dashboard/chat/_chat-layout/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof DashboardChatChatLayoutIndexRouteImport
      parentRoute: typeof DashboardChatChatLayoutRouteRoute
    }
    '/_dashboard/repository/detail/{-$id}': {
      id: '/_dashboard/repository/detail/{-$id}'
      path: '/repository/detail/{-$id}'
      fullPath: '/repository/detail/{-$id}'
      preLoaderRoute: typeof DashboardRepositoryDetailChar123IdChar125RouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile/$userId/works': {
      id: '/_dashboard/profile/$userId/works'
      path: '/works'
      fullPath: '/profile/$userId/works'
      preLoaderRoute: typeof DashboardProfileUserIdWorksRouteImport
      parentRoute: typeof DashboardProfileUserIdRouteRoute
    }
    '/_dashboard/profile/$userId/activities': {
      id: '/_dashboard/profile/$userId/activities'
      path: '/activities'
      fullPath: '/profile/$userId/activities'
      preLoaderRoute: typeof DashboardProfileUserIdActivitiesRouteImport
      parentRoute: typeof DashboardProfileUserIdRouteRoute
    }
    '/_dashboard/material/space/$spaceId': {
      id: '/_dashboard/material/space/$spaceId'
      path: '/space/$spaceId'
      fullPath: '/material/space/$spaceId'
      preLoaderRoute: typeof DashboardMaterialSpaceSpaceIdRouteImport
      parentRoute: typeof DashboardMaterialRouteRoute
    }
    '/_dashboard/doc/$spaceId/$docId': {
      id: '/_dashboard/doc/$spaceId/$docId'
      path: '/doc/$spaceId/$docId'
      fullPath: '/doc/$spaceId/$docId'
      preLoaderRoute: typeof DashboardDocSpaceIdDocIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/chat/discover/my': {
      id: '/_dashboard/chat/discover/my'
      path: '/chat/discover/my'
      fullPath: '/chat/discover/my'
      preLoaderRoute: typeof DashboardChatDiscoverMyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/chat/discover/material/': {
      id: '/_dashboard/chat/discover/material/'
      path: '/chat/discover/material'
      fullPath: '/chat/discover/material/'
      preLoaderRoute: typeof DashboardChatDiscoverMaterialIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/chat/discover/material/my': {
      id: '/_dashboard/chat/discover/material/my'
      path: '/chat/discover/material/my'
      fullPath: '/chat/discover/material/my'
      preLoaderRoute: typeof DashboardChatDiscoverMaterialMyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/chat/_chat-layout/$spaceId/{-$roomId}/{-$messageId}': {
      id: '/_dashboard/chat/_chat-layout/$spaceId/{-$roomId}/{-$messageId}'
      path: '/$spaceId/{-$roomId}/{-$messageId}'
      fullPath: '/chat/$spaceId/{-$roomId}/{-$messageId}'
      preLoaderRoute: typeof DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125RouteImport
      parentRoute: typeof DashboardChatChatLayoutRouteRoute
    }
    '/_dashboard/chat/_chat-layout/$spaceId/doc/$docId': {
      id: '/_dashboard/chat/_chat-layout/$spaceId/doc/$docId'
      path: '/$spaceId/doc/$docId'
      fullPath: '/chat/$spaceId/doc/$docId'
      preLoaderRoute: typeof DashboardChatChatLayoutSpaceIdDocDocIdRouteImport
      parentRoute: typeof DashboardChatChatLayoutRouteRoute
    }
    '/_dashboard/chat/_chat-layout/$spaceId/$roomId/setting': {
      id: '/_dashboard/chat/_chat-layout/$spaceId/$roomId/setting'
      path: '/$spaceId/$roomId/setting'
      fullPath: '/chat/$spaceId/$roomId/setting'
      preLoaderRoute: typeof DashboardChatChatLayoutSpaceIdRoomIdSettingRouteImport
      parentRoute: typeof DashboardChatChatLayoutRouteRoute
    }
  }
}

interface DashboardMaterialRouteRouteChildren {
  DashboardMaterialSpaceSpaceIdRoute: typeof DashboardMaterialSpaceSpaceIdRoute
}

const DashboardMaterialRouteRouteChildren: DashboardMaterialRouteRouteChildren =
  {
    DashboardMaterialSpaceSpaceIdRoute: DashboardMaterialSpaceSpaceIdRoute,
  }

const DashboardMaterialRouteRouteWithChildren =
  DashboardMaterialRouteRoute._addFileChildren(
    DashboardMaterialRouteRouteChildren,
  )

interface DashboardRoleRouteRouteChildren {
  DashboardRoleChar123RoleIdChar125Route: typeof DashboardRoleChar123RoleIdChar125Route
  DashboardRoleIndexRoute: typeof DashboardRoleIndexRoute
}

const DashboardRoleRouteRouteChildren: DashboardRoleRouteRouteChildren = {
  DashboardRoleChar123RoleIdChar125Route:
    DashboardRoleChar123RoleIdChar125Route,
  DashboardRoleIndexRoute: DashboardRoleIndexRoute,
}

const DashboardRoleRouteRouteWithChildren =
  DashboardRoleRouteRoute._addFileChildren(DashboardRoleRouteRouteChildren)

interface DashboardChatChatLayoutRouteRouteChildren {
  DashboardChatChatLayoutIndexRoute: typeof DashboardChatChatLayoutIndexRoute
  DashboardChatChatLayoutSpaceIdRoomIdSettingRoute: typeof DashboardChatChatLayoutSpaceIdRoomIdSettingRoute
  DashboardChatChatLayoutSpaceIdDocDocIdRoute: typeof DashboardChatChatLayoutSpaceIdDocDocIdRoute
  DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125Route: typeof DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125Route
}

const DashboardChatChatLayoutRouteRouteChildren: DashboardChatChatLayoutRouteRouteChildren =
  {
    DashboardChatChatLayoutIndexRoute: DashboardChatChatLayoutIndexRoute,
    DashboardChatChatLayoutSpaceIdRoomIdSettingRoute:
      DashboardChatChatLayoutSpaceIdRoomIdSettingRoute,
    DashboardChatChatLayoutSpaceIdDocDocIdRoute:
      DashboardChatChatLayoutSpaceIdDocDocIdRoute,
    DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125Route:
      DashboardChatChatLayoutSpaceIdChar123RoomIdChar125Char123MessageIdChar125Route,
  }

const DashboardChatChatLayoutRouteRouteWithChildren =
  DashboardChatChatLayoutRouteRoute._addFileChildren(
    DashboardChatChatLayoutRouteRouteChildren,
  )

interface DashboardProfileUserIdRouteRouteChildren {
  DashboardProfileUserIdActivitiesRoute: typeof DashboardProfileUserIdActivitiesRoute
  DashboardProfileUserIdWorksRoute: typeof DashboardProfileUserIdWorksRoute
  DashboardProfileUserIdIndexRoute: typeof DashboardProfileUserIdIndexRoute
}

const DashboardProfileUserIdRouteRouteChildren: DashboardProfileUserIdRouteRouteChildren =
  {
    DashboardProfileUserIdActivitiesRoute:
      DashboardProfileUserIdActivitiesRoute,
    DashboardProfileUserIdWorksRoute: DashboardProfileUserIdWorksRoute,
    DashboardProfileUserIdIndexRoute: DashboardProfileUserIdIndexRoute,
  }

const DashboardProfileUserIdRouteRouteWithChildren =
  DashboardProfileUserIdRouteRoute._addFileChildren(
    DashboardProfileUserIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardMaterialRouteRoute: typeof DashboardMaterialRouteRouteWithChildren
  DashboardRoleRouteRoute: typeof DashboardRoleRouteRouteWithChildren
  DashboardActivitiesRoute: typeof DashboardActivitiesRoute
  DashboardAiImageRoute: typeof DashboardAiImageRoute
  DashboardCollectionRoute: typeof DashboardCollectionRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardResourceRoute: typeof DashboardResourceRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardChatChatLayoutRouteRoute: typeof DashboardChatChatLayoutRouteRouteWithChildren
  DashboardProfileUserIdRouteRoute: typeof DashboardProfileUserIdRouteRouteWithChildren
  DashboardFeedbackIssueIdRoute: typeof DashboardFeedbackIssueIdRoute
  DashboardRepositoryCommitChainRoute: typeof DashboardRepositoryCommitChainRoute
  DashboardRepositoryCreateRoute: typeof DashboardRepositoryCreateRoute
  DashboardFeedbackIndexRoute: typeof DashboardFeedbackIndexRoute
  DashboardRepositoryIndexRoute: typeof DashboardRepositoryIndexRoute
  DashboardChatDiscoverMyRoute: typeof DashboardChatDiscoverMyRoute
  DashboardDocSpaceIdDocIdRoute: typeof DashboardDocSpaceIdDocIdRoute
  DashboardRepositoryDetailChar123IdChar125Route: typeof DashboardRepositoryDetailChar123IdChar125Route
  DashboardChatDiscoverIndexRoute: typeof DashboardChatDiscoverIndexRoute
  DashboardChatDiscoverMaterialMyRoute: typeof DashboardChatDiscoverMaterialMyRoute
  DashboardChatDiscoverMaterialIndexRoute: typeof DashboardChatDiscoverMaterialIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardMaterialRouteRoute: DashboardMaterialRouteRouteWithChildren,
  DashboardRoleRouteRoute: DashboardRoleRouteRouteWithChildren,
  DashboardActivitiesRoute: DashboardActivitiesRoute,
  DashboardAiImageRoute: DashboardAiImageRoute,
  DashboardCollectionRoute: DashboardCollectionRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardResourceRoute: DashboardResourceRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardChatChatLayoutRouteRoute:
    DashboardChatChatLayoutRouteRouteWithChildren,
  DashboardProfileUserIdRouteRoute:
    DashboardProfileUserIdRouteRouteWithChildren,
  DashboardFeedbackIssueIdRoute: DashboardFeedbackIssueIdRoute,
  DashboardRepositoryCommitChainRoute: DashboardRepositoryCommitChainRoute,
  DashboardRepositoryCreateRoute: DashboardRepositoryCreateRoute,
  DashboardFeedbackIndexRoute: DashboardFeedbackIndexRoute,
  DashboardRepositoryIndexRoute: DashboardRepositoryIndexRoute,
  DashboardChatDiscoverMyRoute: DashboardChatDiscoverMyRoute,
  DashboardDocSpaceIdDocIdRoute: DashboardDocSpaceIdDocIdRoute,
  DashboardRepositoryDetailChar123IdChar125Route:
    DashboardRepositoryDetailChar123IdChar125Route,
  DashboardChatDiscoverIndexRoute: DashboardChatDiscoverIndexRoute,
  DashboardChatDiscoverMaterialMyRoute: DashboardChatDiscoverMaterialMyRoute,
  DashboardChatDiscoverMaterialIndexRoute:
    DashboardChatDiscoverMaterialIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ScrollSequenceDemoRoute: ScrollSequenceDemoRoute,
  ScrollSequenceMotionDemoRoute: ScrollSequenceMotionDemoRoute,
  InviteCodeRoute: InviteCodeRoute,
  RoomMapSpaceIdRoomIdRoute: RoomMapSpaceIdRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
