/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as scrollSequenceMotionDemoRouteImport } from './routes/scrollSequenceMotionDemo'
import { Route as scrollSequenceDemoRouteImport } from './routes/scrollSequenceDemo'
import { Route as loginRouteImport } from './routes/login'
import { Route as blocksuiteFrameRouteImport } from './routes/blocksuiteFrame'
import { Route as dashboardRouteImport } from './routes/_dashboard'
import { Route as repositoryIndexRouteImport } from './routes/repository/index'
import { Route as inviteRouteImport } from './routes/invite'
import { Route as settingsRouteImport } from './routes/settings'
import { Route as resourceRouteImport } from './routes/resource'
import { Route as notificationsRouteImport } from './routes/notifications'
import { Route as materialRouteImport } from './routes/material'
import { Route as collectionRouteImport } from './routes/collection'
import { Route as aiImageRouteImport } from './routes/aiImage'
import { Route as activitiesRouteImport } from './routes/activities'
import { Route as homeRouteImport } from './routes/home'
import { Route as roleRouteRouteImport } from './routes/role/route'
import { Route as chatDiscoverIndexRouteImport } from './routes/chat/discover/index'
import { Route as roleIndexRouteImport } from './routes/role/index'
import { Route as roomMapFrameRouteImport } from './routes/roomMapFrame'
import { Route as roleRoleIdRouteImport } from './routes/role/$roleId'
import { Route as repositoryCreateRouteImport } from './routes/repository/create'
import { Route as feedbackRouteImport } from './routes/feedback'
import { Route as profileRouteRouteImport } from './routes/profile/route'
import { Route as chatRouteRouteImport } from './routes/chat/route'
import { Route as repositoryDetailIndexRouteImport } from './routes/repository/detail/index'
import { Route as chatDiscoverMaterialIndexRouteImport } from './routes/chat/discover/material/index'
import { Route as profileIndexRouteImport } from './routes/profile/index'
import { Route as chatIndexRouteImport } from './routes/chat/index'
import { Route as repositoryCommitChainRouteImport } from './routes/repository/commit-chain'
import { Route as profileWorksRouteImport } from './routes/profile/works'
import { Route as profileActivitiesTabRouteImport } from './routes/profile/activitiesTab'
import { Route as spaceMaterialRouteImport } from './routes/spaceMaterial'
import { Route as docRouteImport } from './routes/doc'
import { Route as chatDiscoverMyRouteImport } from './routes/chat/discover/my'
import { Route as chatDiscoverMaterialMyRouteImport } from './routes/chat/discover/material/my'
import { Route as chatSpaceRouteImport } from './routes/chat/space'
import { Route as chatDocRouteImport } from './routes/chat/doc'
import { Route as chatRoomSettingRouteImport } from './routes/chat/room-setting'

const scrollSequenceMotionDemoRoute =
  scrollSequenceMotionDemoRouteImport.update({
    id: '/scroll-sequence-motion-demo',
    path: '/scroll-sequence-motion-demo',
    getParentRoute: () => rootRouteImport,
  } as any)
const scrollSequenceDemoRoute = scrollSequenceDemoRouteImport.update({
  id: '/scroll-sequence-demo',
  path: '/scroll-sequence-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const blocksuiteFrameRoute = blocksuiteFrameRouteImport.update({
  id: '/blocksuite-frame',
  path: '/blocksuite-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRoute = dashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const repositoryIndexRoute = repositoryIndexRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => dashboardRoute,
} as any)
const inviteRoute = inviteRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const settingsRoute = settingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardRoute,
} as any)
const resourceRoute = resourceRouteImport.update({
  id: '/resource',
  path: '/resource',
  getParentRoute: () => dashboardRoute,
} as any)
const notificationsRoute = notificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => dashboardRoute,
} as any)
const materialRoute = materialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => dashboardRoute,
} as any)
const collectionRoute = collectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => dashboardRoute,
} as any)
const aiImageRoute = aiImageRouteImport.update({
  id: '/ai-image',
  path: '/ai-image',
  getParentRoute: () => dashboardRoute,
} as any)
const activitiesRoute = activitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => dashboardRoute,
} as any)
const homeRoute = homeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRoute,
} as any)
const roleRouteRoute = roleRouteRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => dashboardRoute,
} as any)
const chatDiscoverIndexRoute = chatDiscoverIndexRouteImport.update({
  id: '/chat/discover',
  path: '/chat/discover',
  getParentRoute: () => dashboardRoute,
} as any)
const roleIndexRoute = roleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => roleRouteRoute,
} as any)
const roomMapFrameRoute = roomMapFrameRouteImport.update({
  id: '/room-map/$spaceId/$roomId',
  path: '/room-map/$spaceId/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const roleRoleIdRoute = roleRoleIdRouteImport.update({
  id: '/{-$roleId}',
  path: '/{-$roleId}',
  getParentRoute: () => roleRouteRoute,
} as any)
const repositoryCreateRoute = repositoryCreateRouteImport.update({
  id: '/repository/create',
  path: '/repository/create',
  getParentRoute: () => dashboardRoute,
} as any)
const feedbackRoute = feedbackRouteImport.update({
  id: '/feedback/{-$issueId}',
  path: '/feedback/{-$issueId}',
  getParentRoute: () => dashboardRoute,
} as any)
const profileRouteRoute = profileRouteRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => dashboardRoute,
} as any)
const chatRouteRoute = chatRouteRouteImport.update({
  id: '/chat/_chat-layout',
  path: '/chat',
  getParentRoute: () => dashboardRoute,
} as any)
const repositoryDetailIndexRoute = repositoryDetailIndexRouteImport.update({
  id: '/repository/detail/{-$id}',
  path: '/repository/detail/{-$id}',
  getParentRoute: () => dashboardRoute,
} as any)
const chatDiscoverMaterialIndexRoute =
  chatDiscoverMaterialIndexRouteImport.update({
    id: '/material',
    path: '/material',
    getParentRoute: () => chatDiscoverIndexRoute,
  } as any)
const profileIndexRoute = profileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => profileRouteRoute,
} as any)
const chatIndexRoute = chatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => chatRouteRoute,
} as any)
const repositoryCommitChainRoute = repositoryCommitChainRouteImport.update({
  id: '/repository/commit-chain/{-$id}',
  path: '/repository/commit-chain/{-$id}',
  getParentRoute: () => dashboardRoute,
} as any)
const profileWorksRoute = profileWorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => profileRouteRoute,
} as any)
const profileActivitiesTabRoute = profileActivitiesTabRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => profileRouteRoute,
} as any)
const spaceMaterialRoute = spaceMaterialRouteImport.update({
  id: '/material/space/$spaceId',
  path: '/material/space/$spaceId',
  getParentRoute: () => dashboardRoute,
} as any)
const docRoute = docRouteImport.update({
  id: '/doc/$spaceId/$docId',
  path: '/doc/$spaceId/$docId',
  getParentRoute: () => dashboardRoute,
} as any)
const chatDiscoverMyRoute = chatDiscoverMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => chatDiscoverIndexRoute,
} as any)
const chatDiscoverMaterialMyRoute = chatDiscoverMaterialMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => chatDiscoverMaterialIndexRoute,
} as any)
const chatSpaceRoute = chatSpaceRouteImport.update({
  id: '/$spaceId/{-$roomId}/{-$messageId}',
  path: '/$spaceId/{-$roomId}/{-$messageId}',
  getParentRoute: () => chatRouteRoute,
} as any)
const chatDocRoute = chatDocRouteImport.update({
  id: '/$spaceId/doc/$docId',
  path: '/$spaceId/doc/$docId',
  getParentRoute: () => chatRouteRoute,
} as any)
const chatRoomSettingRoute = chatRoomSettingRouteImport.update({
  id: '/$spaceId/$roomId/setting',
  path: '/$spaceId/$roomId/setting',
  getParentRoute: () => chatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeRoute
  '/blocksuite-frame': typeof blocksuiteFrameRoute
  '/login': typeof loginRoute
  '/scroll-sequence-demo': typeof scrollSequenceDemoRoute
  '/scroll-sequence-motion-demo': typeof scrollSequenceMotionDemoRoute
  '/role': typeof roleRouteRouteWithChildren
  '/activities': typeof activitiesRoute
  '/ai-image': typeof aiImageRoute
  '/collection': typeof collectionRoute
  '/material': typeof materialRoute
  '/notifications': typeof notificationsRoute
  '/resource': typeof resourceRoute
  '/settings': typeof settingsRoute
  '/invite/$code': typeof inviteRoute
  '/repository': typeof repositoryIndexRoute
  '/chat': typeof chatRouteRouteWithChildren
  '/profile/$userId': typeof profileRouteRouteWithChildren
  '/feedback/{-$issueId}': typeof feedbackRoute
  '/repository/create': typeof repositoryCreateRoute
  '/role/{-$roleId}': typeof roleRoleIdRoute
  '/room-map/$spaceId/$roomId': typeof roomMapFrameRoute
  '/role/': typeof roleIndexRoute
  '/chat/discover': typeof chatDiscoverIndexRouteWithChildren
  '/chat/discover/my': typeof chatDiscoverMyRoute
  '/doc/$spaceId/$docId': typeof docRoute
  '/material/space/$spaceId': typeof spaceMaterialRoute
  '/profile/$userId/activities': typeof profileActivitiesTabRoute
  '/profile/$userId/works': typeof profileWorksRoute
  '/repository/commit-chain/{-$id}': typeof repositoryCommitChainRoute
  '/chat/': typeof chatIndexRoute
  '/profile/$userId/': typeof profileIndexRoute
  '/chat/discover/material': typeof chatDiscoverMaterialIndexRouteWithChildren
  '/repository/detail/{-$id}': typeof repositoryDetailIndexRoute
  '/chat/discover/material/my': typeof chatDiscoverMaterialMyRoute
  '/chat/$spaceId/$roomId/setting': typeof chatRoomSettingRoute
  '/chat/$spaceId/doc/$docId': typeof chatDocRoute
  '/chat/$spaceId/{-$roomId}/{-$messageId}': typeof chatSpaceRoute
}
export interface FileRoutesByTo {
  '/blocksuite-frame': typeof blocksuiteFrameRoute
  '/login': typeof loginRoute
  '/scroll-sequence-demo': typeof scrollSequenceDemoRoute
  '/scroll-sequence-motion-demo': typeof scrollSequenceMotionDemoRoute
  '/': typeof homeRoute
  '/activities': typeof activitiesRoute
  '/ai-image': typeof aiImageRoute
  '/collection': typeof collectionRoute
  '/material': typeof materialRoute
  '/notifications': typeof notificationsRoute
  '/resource': typeof resourceRoute
  '/settings': typeof settingsRoute
  '/invite/$code': typeof inviteRoute
  '/repository': typeof repositoryIndexRoute
  '/feedback/{-$issueId}': typeof feedbackRoute
  '/repository/create': typeof repositoryCreateRoute
  '/role/{-$roleId}': typeof roleRoleIdRoute
  '/room-map/$spaceId/$roomId': typeof roomMapFrameRoute
  '/role': typeof roleIndexRoute
  '/chat/discover': typeof chatDiscoverIndexRouteWithChildren
  '/chat/discover/my': typeof chatDiscoverMyRoute
  '/doc/$spaceId/$docId': typeof docRoute
  '/material/space/$spaceId': typeof spaceMaterialRoute
  '/profile/$userId/activities': typeof profileActivitiesTabRoute
  '/profile/$userId/works': typeof profileWorksRoute
  '/repository/commit-chain/{-$id}': typeof repositoryCommitChainRoute
  '/chat': typeof chatIndexRoute
  '/profile/$userId': typeof profileIndexRoute
  '/chat/discover/material': typeof chatDiscoverMaterialIndexRouteWithChildren
  '/repository/detail/{-$id}': typeof repositoryDetailIndexRoute
  '/chat/discover/material/my': typeof chatDiscoverMaterialMyRoute
  '/chat/$spaceId/$roomId/setting': typeof chatRoomSettingRoute
  '/chat/$spaceId/doc/$docId': typeof chatDocRoute
  '/chat/$spaceId/{-$roomId}/{-$messageId}': typeof chatSpaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof dashboardRouteWithChildren
  '/blocksuite-frame': typeof blocksuiteFrameRoute
  '/login': typeof loginRoute
  '/scroll-sequence-demo': typeof scrollSequenceDemoRoute
  '/scroll-sequence-motion-demo': typeof scrollSequenceMotionDemoRoute
  '/_dashboard/role': typeof roleRouteRouteWithChildren
  '/_dashboard/': typeof homeRoute
  '/_dashboard/activities': typeof activitiesRoute
  '/_dashboard/ai-image': typeof aiImageRoute
  '/_dashboard/collection': typeof collectionRoute
  '/_dashboard/material': typeof materialRoute
  '/_dashboard/notifications': typeof notificationsRoute
  '/_dashboard/resource': typeof resourceRoute
  '/_dashboard/settings': typeof settingsRoute
  '/invite/$code': typeof inviteRoute
  '/_dashboard/repository': typeof repositoryIndexRoute
  '/_dashboard/chat/_chat-layout': typeof chatRouteRouteWithChildren
  '/_dashboard/profile/$userId': typeof profileRouteRouteWithChildren
  '/_dashboard/feedback/{-$issueId}': typeof feedbackRoute
  '/_dashboard/repository/create': typeof repositoryCreateRoute
  '/_dashboard/role/{-$roleId}': typeof roleRoleIdRoute
  '/room-map/$spaceId/$roomId': typeof roomMapFrameRoute
  '/_dashboard/role/': typeof roleIndexRoute
  '/_dashboard/chat/discover': typeof chatDiscoverIndexRouteWithChildren
  '/_dashboard/chat/discover/my': typeof chatDiscoverMyRoute
  '/_dashboard/doc/$spaceId/$docId': typeof docRoute
  '/_dashboard/material/space/$spaceId': typeof spaceMaterialRoute
  '/_dashboard/profile/$userId/activities': typeof profileActivitiesTabRoute
  '/_dashboard/profile/$userId/works': typeof profileWorksRoute
  '/_dashboard/repository/commit-chain/{-$id}': typeof repositoryCommitChainRoute
  '/_dashboard/chat/_chat-layout/': typeof chatIndexRoute
  '/_dashboard/profile/$userId/': typeof profileIndexRoute
  '/_dashboard/chat/discover/material': typeof chatDiscoverMaterialIndexRouteWithChildren
  '/_dashboard/repository/detail/{-$id}': typeof repositoryDetailIndexRoute
  '/_dashboard/chat/discover/material/my': typeof chatDiscoverMaterialMyRoute
  '/_dashboard/chat/_chat-layout/$spaceId/$roomId/setting': typeof chatRoomSettingRoute
  '/_dashboard/chat/_chat-layout/$spaceId/doc/$docId': typeof chatDocRoute
  '/_dashboard/chat/_chat-layout/$spaceId/{-$roomId}/{-$messageId}': typeof chatSpaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocksuite-frame'
    | '/login'
    | '/scroll-sequence-demo'
    | '/scroll-sequence-motion-demo'
    | '/role'
    | '/activities'
    | '/ai-image'
    | '/collection'
    | '/material'
    | '/notifications'
    | '/resource'
    | '/settings'
    | '/invite/$code'
    | '/repository'
    | '/chat'
    | '/profile/$userId'
    | '/feedback/{-$issueId}'
    | '/repository/create'
    | '/role/{-$roleId}'
    | '/room-map/$spaceId/$roomId'
    | '/role/'
    | '/chat/discover'
    | '/chat/discover/my'
    | '/doc/$spaceId/$docId'
    | '/material/space/$spaceId'
    | '/profile/$userId/activities'
    | '/profile/$userId/works'
    | '/repository/commit-chain/{-$id}'
    | '/chat/'
    | '/profile/$userId/'
    | '/chat/discover/material'
    | '/repository/detail/{-$id}'
    | '/chat/discover/material/my'
    | '/chat/$spaceId/$roomId/setting'
    | '/chat/$spaceId/doc/$docId'
    | '/chat/$spaceId/{-$roomId}/{-$messageId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blocksuite-frame'
    | '/login'
    | '/scroll-sequence-demo'
    | '/scroll-sequence-motion-demo'
    | '/'
    | '/activities'
    | '/ai-image'
    | '/collection'
    | '/material'
    | '/notifications'
    | '/resource'
    | '/settings'
    | '/invite/$code'
    | '/repository'
    | '/feedback/{-$issueId}'
    | '/repository/create'
    | '/role/{-$roleId}'
    | '/room-map/$spaceId/$roomId'
    | '/role'
    | '/chat/discover'
    | '/chat/discover/my'
    | '/doc/$spaceId/$docId'
    | '/material/space/$spaceId'
    | '/profile/$userId/activities'
    | '/profile/$userId/works'
    | '/repository/commit-chain/{-$id}'
    | '/chat'
    | '/profile/$userId'
    | '/chat/discover/material'
    | '/repository/detail/{-$id}'
    | '/chat/discover/material/my'
    | '/chat/$spaceId/$roomId/setting'
    | '/chat/$spaceId/doc/$docId'
    | '/chat/$spaceId/{-$roomId}/{-$messageId}'
  id:
    | '__root__'
    | '/_dashboard'
    | '/blocksuite-frame'
    | '/login'
    | '/scroll-sequence-demo'
    | '/scroll-sequence-motion-demo'
    | '/_dashboard/role'
    | '/_dashboard/'
    | '/_dashboard/activities'
    | '/_dashboard/ai-image'
    | '/_dashboard/collection'
    | '/_dashboard/material'
    | '/_dashboard/notifications'
    | '/_dashboard/resource'
    | '/_dashboard/settings'
    | '/invite/$code'
    | '/_dashboard/repository'
    | '/_dashboard/chat/_chat-layout'
    | '/_dashboard/profile/$userId'
    | '/_dashboard/feedback/{-$issueId}'
    | '/_dashboard/repository/create'
    | '/_dashboard/role/{-$roleId}'
    | '/room-map/$spaceId/$roomId'
    | '/_dashboard/role/'
    | '/_dashboard/chat/discover'
    | '/_dashboard/chat/discover/my'
    | '/_dashboard/doc/$spaceId/$docId'
    | '/_dashboard/material/space/$spaceId'
    | '/_dashboard/profile/$userId/activities'
    | '/_dashboard/profile/$userId/works'
    | '/_dashboard/repository/commit-chain/{-$id}'
    | '/_dashboard/chat/_chat-layout/'
    | '/_dashboard/profile/$userId/'
    | '/_dashboard/chat/discover/material'
    | '/_dashboard/repository/detail/{-$id}'
    | '/_dashboard/chat/discover/material/my'
    | '/_dashboard/chat/_chat-layout/$spaceId/$roomId/setting'
    | '/_dashboard/chat/_chat-layout/$spaceId/doc/$docId'
    | '/_dashboard/chat/_chat-layout/$spaceId/{-$roomId}/{-$messageId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRoute: typeof dashboardRouteWithChildren
  blocksuiteFrameRoute: typeof blocksuiteFrameRoute
  loginRoute: typeof loginRoute
  scrollSequenceDemoRoute: typeof scrollSequenceDemoRoute
  scrollSequenceMotionDemoRoute: typeof scrollSequenceMotionDemoRoute
  inviteRoute: typeof inviteRoute
  roomMapFrameRoute: typeof roomMapFrameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scroll-sequence-motion-demo': {
      id: '/scroll-sequence-motion-demo'
      path: '/scroll-sequence-motion-demo'
      fullPath: '/scroll-sequence-motion-demo'
      preLoaderRoute: typeof scrollSequenceMotionDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll-sequence-demo': {
      id: '/scroll-sequence-demo'
      path: '/scroll-sequence-demo'
      fullPath: '/scroll-sequence-demo'
      preLoaderRoute: typeof scrollSequenceDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocksuite-frame': {
      id: '/blocksuite-frame'
      path: '/blocksuite-frame'
      fullPath: '/blocksuite-frame'
      preLoaderRoute: typeof blocksuiteFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof dashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/repository': {
      id: '/_dashboard/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof repositoryIndexRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof inviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof settingsRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/resource': {
      id: '/_dashboard/resource'
      path: '/resource'
      fullPath: '/resource'
      preLoaderRoute: typeof resourceRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/notifications': {
      id: '/_dashboard/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof notificationsRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/material': {
      id: '/_dashboard/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof materialRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/collection': {
      id: '/_dashboard/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof collectionRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/ai-image': {
      id: '/_dashboard/ai-image'
      path: '/ai-image'
      fullPath: '/ai-image'
      preLoaderRoute: typeof aiImageRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/activities': {
      id: '/_dashboard/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof activitiesRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/role': {
      id: '/_dashboard/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof roleRouteRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/chat/discover': {
      id: '/_dashboard/chat/discover'
      path: '/chat/discover'
      fullPath: '/chat/discover'
      preLoaderRoute: typeof chatDiscoverIndexRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/role/': {
      id: '/_dashboard/role/'
      path: '/'
      fullPath: '/role/'
      preLoaderRoute: typeof roleIndexRouteImport
      parentRoute: typeof roleRouteRoute
    }
    '/room-map/$spaceId/$roomId': {
      id: '/room-map/$spaceId/$roomId'
      path: '/room-map/$spaceId/$roomId'
      fullPath: '/room-map/$spaceId/$roomId'
      preLoaderRoute: typeof roomMapFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/role/{-$roleId}': {
      id: '/_dashboard/role/{-$roleId}'
      path: '/{-$roleId}'
      fullPath: '/role/{-$roleId}'
      preLoaderRoute: typeof roleRoleIdRouteImport
      parentRoute: typeof roleRouteRoute
    }
    '/_dashboard/repository/create': {
      id: '/_dashboard/repository/create'
      path: '/repository/create'
      fullPath: '/repository/create'
      preLoaderRoute: typeof repositoryCreateRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/feedback/{-$issueId}': {
      id: '/_dashboard/feedback/{-$issueId}'
      path: '/feedback/{-$issueId}'
      fullPath: '/feedback/{-$issueId}'
      preLoaderRoute: typeof feedbackRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/profile/$userId': {
      id: '/_dashboard/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof profileRouteRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/chat/_chat-layout': {
      id: '/_dashboard/chat/_chat-layout'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof chatRouteRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/repository/detail/{-$id}': {
      id: '/_dashboard/repository/detail/{-$id}'
      path: '/repository/detail/{-$id}'
      fullPath: '/repository/detail/{-$id}'
      preLoaderRoute: typeof repositoryDetailIndexRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/chat/discover/material': {
      id: '/_dashboard/chat/discover/material'
      path: '/material'
      fullPath: '/chat/discover/material'
      preLoaderRoute: typeof chatDiscoverMaterialIndexRouteImport
      parentRoute: typeof chatDiscoverIndexRoute
    }
    '/_dashboard/profile/$userId/': {
      id: '/_dashboard/profile/$userId/'
      path: '/'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof profileIndexRouteImport
      parentRoute: typeof profileRouteRoute
    }
    '/_dashboard/chat/_chat-layout/': {
      id: '/_dashboard/chat/_chat-layout/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof chatIndexRouteImport
      parentRoute: typeof chatRouteRoute
    }
    '/_dashboard/repository/commit-chain/{-$id}': {
      id: '/_dashboard/repository/commit-chain/{-$id}'
      path: '/repository/commit-chain/{-$id}'
      fullPath: '/repository/commit-chain/{-$id}'
      preLoaderRoute: typeof repositoryCommitChainRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/profile/$userId/works': {
      id: '/_dashboard/profile/$userId/works'
      path: '/works'
      fullPath: '/profile/$userId/works'
      preLoaderRoute: typeof profileWorksRouteImport
      parentRoute: typeof profileRouteRoute
    }
    '/_dashboard/profile/$userId/activities': {
      id: '/_dashboard/profile/$userId/activities'
      path: '/activities'
      fullPath: '/profile/$userId/activities'
      preLoaderRoute: typeof profileActivitiesTabRouteImport
      parentRoute: typeof profileRouteRoute
    }
    '/_dashboard/material/space/$spaceId': {
      id: '/_dashboard/material/space/$spaceId'
      path: '/material/space/$spaceId'
      fullPath: '/material/space/$spaceId'
      preLoaderRoute: typeof spaceMaterialRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/doc/$spaceId/$docId': {
      id: '/_dashboard/doc/$spaceId/$docId'
      path: '/doc/$spaceId/$docId'
      fullPath: '/doc/$spaceId/$docId'
      preLoaderRoute: typeof docRouteImport
      parentRoute: typeof dashboardRoute
    }
    '/_dashboard/chat/discover/my': {
      id: '/_dashboard/chat/discover/my'
      path: '/my'
      fullPath: '/chat/discover/my'
      preLoaderRoute: typeof chatDiscoverMyRouteImport
      parentRoute: typeof chatDiscoverIndexRoute
    }
    '/_dashboard/chat/discover/material/my': {
      id: '/_dashboard/chat/discover/material/my'
      path: '/my'
      fullPath: '/chat/discover/material/my'
      preLoaderRoute: typeof chatDiscoverMaterialMyRouteImport
      parentRoute: typeof chatDiscoverMaterialIndexRoute
    }
    '/_dashboard/chat/_chat-layout/$spaceId/{-$roomId}/{-$messageId}': {
      id: '/_dashboard/chat/_chat-layout/$spaceId/{-$roomId}/{-$messageId}'
      path: '/$spaceId/{-$roomId}/{-$messageId}'
      fullPath: '/chat/$spaceId/{-$roomId}/{-$messageId}'
      preLoaderRoute: typeof chatSpaceRouteImport
      parentRoute: typeof chatRouteRoute
    }
    '/_dashboard/chat/_chat-layout/$spaceId/doc/$docId': {
      id: '/_dashboard/chat/_chat-layout/$spaceId/doc/$docId'
      path: '/$spaceId/doc/$docId'
      fullPath: '/chat/$spaceId/doc/$docId'
      preLoaderRoute: typeof chatDocRouteImport
      parentRoute: typeof chatRouteRoute
    }
    '/_dashboard/chat/_chat-layout/$spaceId/$roomId/setting': {
      id: '/_dashboard/chat/_chat-layout/$spaceId/$roomId/setting'
      path: '/$spaceId/$roomId/setting'
      fullPath: '/chat/$spaceId/$roomId/setting'
      preLoaderRoute: typeof chatRoomSettingRouteImport
      parentRoute: typeof chatRouteRoute
    }
  }
}

interface roleRouteRouteChildren {
  roleRoleIdRoute: typeof roleRoleIdRoute
  roleIndexRoute: typeof roleIndexRoute
}

const roleRouteRouteChildren: roleRouteRouteChildren = {
  roleRoleIdRoute: roleRoleIdRoute,
  roleIndexRoute: roleIndexRoute,
}

const roleRouteRouteWithChildren = roleRouteRoute._addFileChildren(
  roleRouteRouteChildren,
)

interface chatRouteRouteChildren {
  chatIndexRoute: typeof chatIndexRoute
  chatRoomSettingRoute: typeof chatRoomSettingRoute
  chatDocRoute: typeof chatDocRoute
  chatSpaceRoute: typeof chatSpaceRoute
}

const chatRouteRouteChildren: chatRouteRouteChildren = {
  chatIndexRoute: chatIndexRoute,
  chatRoomSettingRoute: chatRoomSettingRoute,
  chatDocRoute: chatDocRoute,
  chatSpaceRoute: chatSpaceRoute,
}

const chatRouteRouteWithChildren = chatRouteRoute._addFileChildren(
  chatRouteRouteChildren,
)

interface profileRouteRouteChildren {
  profileActivitiesTabRoute: typeof profileActivitiesTabRoute
  profileWorksRoute: typeof profileWorksRoute
  profileIndexRoute: typeof profileIndexRoute
}

const profileRouteRouteChildren: profileRouteRouteChildren = {
  profileActivitiesTabRoute: profileActivitiesTabRoute,
  profileWorksRoute: profileWorksRoute,
  profileIndexRoute: profileIndexRoute,
}

const profileRouteRouteWithChildren = profileRouteRoute._addFileChildren(
  profileRouteRouteChildren,
)

interface chatDiscoverMaterialIndexRouteChildren {
  chatDiscoverMaterialMyRoute: typeof chatDiscoverMaterialMyRoute
}

const chatDiscoverMaterialIndexRouteChildren: chatDiscoverMaterialIndexRouteChildren =
  {
    chatDiscoverMaterialMyRoute: chatDiscoverMaterialMyRoute,
  }

const chatDiscoverMaterialIndexRouteWithChildren =
  chatDiscoverMaterialIndexRoute._addFileChildren(
    chatDiscoverMaterialIndexRouteChildren,
  )

interface chatDiscoverIndexRouteChildren {
  chatDiscoverMyRoute: typeof chatDiscoverMyRoute
  chatDiscoverMaterialIndexRoute: typeof chatDiscoverMaterialIndexRouteWithChildren
}

const chatDiscoverIndexRouteChildren: chatDiscoverIndexRouteChildren = {
  chatDiscoverMyRoute: chatDiscoverMyRoute,
  chatDiscoverMaterialIndexRoute: chatDiscoverMaterialIndexRouteWithChildren,
}

const chatDiscoverIndexRouteWithChildren =
  chatDiscoverIndexRoute._addFileChildren(chatDiscoverIndexRouteChildren)

interface dashboardRouteChildren {
  roleRouteRoute: typeof roleRouteRouteWithChildren
  homeRoute: typeof homeRoute
  activitiesRoute: typeof activitiesRoute
  aiImageRoute: typeof aiImageRoute
  collectionRoute: typeof collectionRoute
  materialRoute: typeof materialRoute
  notificationsRoute: typeof notificationsRoute
  resourceRoute: typeof resourceRoute
  settingsRoute: typeof settingsRoute
  repositoryIndexRoute: typeof repositoryIndexRoute
  chatRouteRoute: typeof chatRouteRouteWithChildren
  profileRouteRoute: typeof profileRouteRouteWithChildren
  feedbackRoute: typeof feedbackRoute
  repositoryCreateRoute: typeof repositoryCreateRoute
  chatDiscoverIndexRoute: typeof chatDiscoverIndexRouteWithChildren
  docRoute: typeof docRoute
  spaceMaterialRoute: typeof spaceMaterialRoute
  repositoryCommitChainRoute: typeof repositoryCommitChainRoute
  repositoryDetailIndexRoute: typeof repositoryDetailIndexRoute
}

const dashboardRouteChildren: dashboardRouteChildren = {
  roleRouteRoute: roleRouteRouteWithChildren,
  homeRoute: homeRoute,
  activitiesRoute: activitiesRoute,
  aiImageRoute: aiImageRoute,
  collectionRoute: collectionRoute,
  materialRoute: materialRoute,
  notificationsRoute: notificationsRoute,
  resourceRoute: resourceRoute,
  settingsRoute: settingsRoute,
  repositoryIndexRoute: repositoryIndexRoute,
  chatRouteRoute: chatRouteRouteWithChildren,
  profileRouteRoute: profileRouteRouteWithChildren,
  feedbackRoute: feedbackRoute,
  repositoryCreateRoute: repositoryCreateRoute,
  chatDiscoverIndexRoute: chatDiscoverIndexRouteWithChildren,
  docRoute: docRoute,
  spaceMaterialRoute: spaceMaterialRoute,
  repositoryCommitChainRoute: repositoryCommitChainRoute,
  repositoryDetailIndexRoute: repositoryDetailIndexRoute,
}

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(
  dashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRoute: dashboardRouteWithChildren,
  blocksuiteFrameRoute: blocksuiteFrameRoute,
  loginRoute: loginRoute,
  scrollSequenceDemoRoute: scrollSequenceDemoRoute,
  scrollSequenceMotionDemoRoute: scrollSequenceMotionDemoRoute,
  inviteRoute: inviteRoute,
  roomMapFrameRoute: roomMapFrameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
