/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { TuanChat } from './TuanChat';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AbilityFieldUpdateRequest } from './models/AbilityFieldUpdateRequest';
export type { AbilityFieldUpdateRequest2 } from './models/AbilityFieldUpdateRequest2';
export type { AbilityPageRequest } from './models/AbilityPageRequest';
export type { AbilitySetRequest } from './models/AbilitySetRequest';
export type { AbilityUpdateRequest } from './models/AbilityUpdateRequest';
export type { AbilityUpdateRequest2 } from './models/AbilityUpdateRequest2';
export type { AiGatewayRelayRequest } from './models/AiGatewayRelayRequest';
export type { ApiResult } from './models/ApiResult';
export type { ApiResultBlocksuiteDocUpdatePushResponse } from './models/ApiResultBlocksuiteDocUpdatePushResponse';
export type { ApiResultBlocksuiteDocUpdatesResponse } from './models/ApiResultBlocksuiteDocUpdatesResponse';
export type { ApiResultBoolean } from './models/ApiResultBoolean';
export type { ApiResultChatMessageResponse } from './models/ApiResultChatMessageResponse';
export type { ApiResultCollection } from './models/ApiResultCollection';
export type { ApiResultCollectionList } from './models/ApiResultCollectionList';
export type { ApiResultCollectionListItem } from './models/ApiResultCollectionListItem';
export type { ApiResultCollectionListResponse } from './models/ApiResultCollectionListResponse';
export type { ApiResultCommentVO } from './models/ApiResultCommentVO';
export type { ApiResultCommunityResponse } from './models/ApiResultCommunityResponse';
export type { ApiResultCursorPageBaseResponseChatMessageResponse } from './models/ApiResultCursorPageBaseResponseChatMessageResponse';
export type { ApiResultCursorPageBaseResponseFeedWithStatsResponse } from './models/ApiResultCursorPageBaseResponseFeedWithStatsResponse';
export type { ApiResultCursorPageBaseResponsePostListWithStatsResponse } from './models/ApiResultCursorPageBaseResponsePostListWithStatsResponse';
export type { ApiResultDouble } from './models/ApiResultDouble';
export type { ApiResultFeedWithStatsResponse } from './models/ApiResultFeedWithStatsResponse';
export type { ApiResultFriendCheckResponse } from './models/ApiResultFriendCheckResponse';
export type { ApiResultInteger } from './models/ApiResultInteger';
export type { ApiResultListClassificationItemResponse } from './models/ApiResultListClassificationItemResponse';
export type { ApiResultListClassificationResponse } from './models/ApiResultListClassificationResponse';
export type { ApiResultListCommentVO } from './models/ApiResultListCommentVO';
export type { ApiResultListCommunityResponse } from './models/ApiResultListCommunityResponse';
export type { ApiResultListFriendResponse } from './models/ApiResultListFriendResponse';
export type { ApiResultListMarkStatusResp } from './models/ApiResultListMarkStatusResp';
export type { ApiResultListMessage } from './models/ApiResultListMessage';
export type { ApiResultListMessageDirectResponse } from './models/ApiResultListMessageDirectResponse';
export type { ApiResultListMessageSessionResponse } from './models/ApiResultListMessageSessionResponse';
export type { ApiResultListRoleAbility } from './models/ApiResultListRoleAbility';
export type { ApiResultListRoleAvatar } from './models/ApiResultListRoleAvatar';
export type { ApiResultListRoomMember } from './models/ApiResultListRoomMember';
export type { ApiResultListSpace } from './models/ApiResultListSpace';
export type { ApiResultListSpaceDocResponse } from './models/ApiResultListSpaceDocResponse';
export type { ApiResultListSpaceMember } from './models/ApiResultListSpaceMember';
export type { ApiResultListSpaceUserDocResponse } from './models/ApiResultListSpaceUserDocResponse';
export type { ApiResultListSticker } from './models/ApiResultListSticker';
export type { ApiResultListTag } from './models/ApiResultListTag';
export type { ApiResultListUserRole } from './models/ApiResultListUserRole';
export type { ApiResultLong } from './models/ApiResultLong';
export type { ApiResultMapLongInteger } from './models/ApiResultMapLongInteger';
export type { ApiResultMapStringInteger } from './models/ApiResultMapStringInteger';
export type { ApiResultMessage } from './models/ApiResultMessage';
export type { ApiResultMessageDirectResponse } from './models/ApiResultMessageDirectResponse';
export type { ApiResultMessageSession } from './models/ApiResultMessageSession';
export type { ApiResultMessageSessionResponse } from './models/ApiResultMessageSessionResponse';
export type { ApiResultMomentFeedTotalStatsResponse } from './models/ApiResultMomentFeedTotalStatsResponse';
export type { ApiResultObject } from './models/ApiResultObject';
export type { ApiResultOssResp } from './models/ApiResultOssResp';
export type { ApiResultPageBaseRespCollection } from './models/ApiResultPageBaseRespCollection';
export type { ApiResultPageBaseRespCollectionList } from './models/ApiResultPageBaseRespCollectionList';
export type { ApiResultPageBaseRespCollectionListResponse } from './models/ApiResultPageBaseRespCollectionListResponse';
export type { ApiResultPageBaseRespFollowResponse } from './models/ApiResultPageBaseRespFollowResponse';
export type { ApiResultPageBaseRespFriendReqResponse } from './models/ApiResultPageBaseRespFriendReqResponse';
export type { ApiResultPageBaseRespRatingVO } from './models/ApiResultPageBaseRespRatingVO';
export type { ApiResultPageBaseRespRepository } from './models/ApiResultPageBaseRespRepository';
export type { ApiResultPageBaseRespResourceResponse } from './models/ApiResultPageBaseRespResourceResponse';
export type { ApiResultPageBaseRespRoleAbility } from './models/ApiResultPageBaseRespRoleAbility';
export type { ApiResultPageBaseRespRuleResponse } from './models/ApiResultPageBaseRespRuleResponse';
export type { ApiResultPageBaseRespUserRole } from './models/ApiResultPageBaseRespUserRole';
export type { ApiResultPostWithStatsResponse } from './models/ApiResultPostWithStatsResponse';
export type { ApiResultRatingVO } from './models/ApiResultRatingVO';
export type { ApiResultRepository } from './models/ApiResultRepository';
export type { ApiResultResourceResponse } from './models/ApiResultResourceResponse';
export type { ApiResultRoleAbility } from './models/ApiResultRoleAbility';
export type { ApiResultRoleAvatar } from './models/ApiResultRoleAvatar';
export type { ApiResultRoom } from './models/ApiResultRoom';
export type { ApiResultRoomDndMapResponse } from './models/ApiResultRoomDndMapResponse';
export type { ApiResultRoomDndMapTokenResponse } from './models/ApiResultRoomDndMapTokenResponse';
export type { ApiResultRoomListResponse } from './models/ApiResultRoomListResponse';
export type { ApiResultRule } from './models/ApiResultRule';
export type { ApiResultSpace } from './models/ApiResultSpace';
export type { ApiResultSpaceDocResponse } from './models/ApiResultSpaceDocResponse';
export type { ApiResultSpaceSidebarTreeResponse } from './models/ApiResultSpaceSidebarTreeResponse';
export type { ApiResultSpaceUserDocResponse } from './models/ApiResultSpaceUserDocResponse';
export type { ApiResultString } from './models/ApiResultString';
export type { ApiResultTag } from './models/ApiResultTag';
export type { ApiResultUserInfoResponse } from './models/ApiResultUserInfoResponse';
export type { ApiResultUserPrivateInfoResponse } from './models/ApiResultUserPrivateInfoResponse';
export type { ApiResultUserProfileInfoResponse } from './models/ApiResultUserProfileInfoResponse';
export type { ApiResultUserRole } from './models/ApiResultUserRole';
export type { ApiResultVoid } from './models/ApiResultVoid';
export type { BatchCounterQueryDTO } from './models/BatchCounterQueryDTO';
export { BatchMarkStatusRequest } from './models/BatchMarkStatusRequest';
export type { BlocksuiteDocCompactRequest } from './models/BlocksuiteDocCompactRequest';
export type { BlocksuiteDocUpdatePushRequest } from './models/BlocksuiteDocUpdatePushRequest';
export type { BlocksuiteDocUpdatePushResponse } from './models/BlocksuiteDocUpdatePushResponse';
export type { BlocksuiteDocUpdatesResponse } from './models/BlocksuiteDocUpdatesResponse';
export type { BlocksuiteDocUpsertRequest } from './models/BlocksuiteDocUpsertRequest';
export type { ChatMessagePageRequest } from './models/ChatMessagePageRequest';
export type { ChatMessageRequest } from './models/ChatMessageRequest';
export type { ChatMessageResponse } from './models/ChatMessageResponse';
export type { Choice } from './models/Choice';
export type { ClassificationByItemRequest } from './models/ClassificationByItemRequest';
export type { ClassificationItemResponse } from './models/ClassificationItemResponse';
export type { ClassificationResponse } from './models/ClassificationResponse';
export type { ClueMessage } from './models/ClueMessage';
export type { Collection } from './models/Collection';
export type { CollectionAddRequest } from './models/CollectionAddRequest';
export type { CollectionCheckRequest } from './models/CollectionCheckRequest';
export type { CollectionCountRequest } from './models/CollectionCountRequest';
export type { CollectionList } from './models/CollectionList';
export type { CollectionListAddRequest } from './models/CollectionListAddRequest';
export type { CollectionListItem } from './models/CollectionListItem';
export type { CollectionListItemAddRequest } from './models/CollectionListItemAddRequest';
export type { CollectionListItemBatchAddRequest } from './models/CollectionListItemBatchAddRequest';
export type { CollectionListItemPageRequest } from './models/CollectionListItemPageRequest';
export type { CollectionListItemRemoveRequest } from './models/CollectionListItemRemoveRequest';
export type { CollectionListResponse } from './models/CollectionListResponse';
export type { CollectionListUpdateRequest } from './models/CollectionListUpdateRequest';
export type { CollectionPageRequest } from './models/CollectionPageRequest';
export type { CollectionResourcePageRequest } from './models/CollectionResourcePageRequest';
export type { CommandRequestExtra } from './models/CommandRequestExtra';
export type { CommentAddRequest } from './models/CommentAddRequest';
export type { CommentCountRequest } from './models/CommentCountRequest';
export type { CommentPageRequest } from './models/CommentPageRequest';
export type { CommentVO } from './models/CommentVO';
export type { CommunityCreateRequest } from './models/CommunityCreateRequest';
export type { CommunityResponse } from './models/CommunityResponse';
export type { CommunityUpdateRequest } from './models/CommunityUpdateRequest';
export type { CounterOperationDTO } from './models/CounterOperationDTO';
export type { CursorPageBaseResponseChatMessageResponse } from './models/CursorPageBaseResponseChatMessageResponse';
export type { CursorPageBaseResponseFeedWithStatsResponse } from './models/CursorPageBaseResponseFeedWithStatsResponse';
export type { CursorPageBaseResponsePostListWithStatsResponse } from './models/CursorPageBaseResponsePostListWithStatsResponse';
export type { DiceResult } from './models/DiceResult';
export type { DocCardExtra } from './models/DocCardExtra';
export type { EffectMessage } from './models/EffectMessage';
export type { FeedPageRequest } from './models/FeedPageRequest';
export type { FeedWithStatsResponse } from './models/FeedWithStatsResponse';
export type { FileMessage } from './models/FileMessage';
export type { FollowResponse } from './models/FollowResponse';
export type { ForwardMessage } from './models/ForwardMessage';
export type { FriendBlockRequest } from './models/FriendBlockRequest';
export type { FriendCheckRequest } from './models/FriendCheckRequest';
export type { FriendCheckResponse } from './models/FriendCheckResponse';
export type { FriendDeleteRequest } from './models/FriendDeleteRequest';
export type { FriendListRequest } from './models/FriendListRequest';
export type { FriendReqHandleRequest } from './models/FriendReqHandleRequest';
export type { FriendReqResponse } from './models/FriendReqResponse';
export type { FriendReqSendRequest } from './models/FriendReqSendRequest';
export type { FriendResponse } from './models/FriendResponse';
export type { HistoryMessageRequest } from './models/HistoryMessageRequest';
export type { ImageMessage } from './models/ImageMessage';
export type { LeaderTransferRequest } from './models/LeaderTransferRequest';
export { MarkCountRequest } from './models/MarkCountRequest';
export { MarkRecordRequest } from './models/MarkRecordRequest';
export type { MarkStatusResp } from './models/MarkStatusResp';
export type { MarkTarget } from './models/MarkTarget';
export type { Message } from './models/Message';
export type { MessageBySyncIdRequest } from './models/MessageBySyncIdRequest';
export type { MessageDirectReadUpdateRequest } from './models/MessageDirectReadUpdateRequest';
export type { MessageDirectRecallRequest } from './models/MessageDirectRecallRequest';
export type { MessageDirectResponse } from './models/MessageDirectResponse';
export type { MessageDirectSendRequest } from './models/MessageDirectSendRequest';
export type { MessageExtra } from './models/MessageExtra';
export type { MessageSession } from './models/MessageSession';
export type { MessageSessionResponse } from './models/MessageSessionResponse';
export type { MomentFeedRequest } from './models/MomentFeedRequest';
export type { MomentFeedTotalStatsResponse } from './models/MomentFeedTotalStatsResponse';
export type { OpenAiChatCompletionRequest } from './models/OpenAiChatCompletionRequest';
export type { OpenAiChatCompletionResponse } from './models/OpenAiChatCompletionResponse';
export type { OssResp } from './models/OssResp';
export type { PageBaseRequest } from './models/PageBaseRequest';
export type { PageBaseRespCollection } from './models/PageBaseRespCollection';
export type { PageBaseRespCollectionList } from './models/PageBaseRespCollectionList';
export type { PageBaseRespCollectionListResponse } from './models/PageBaseRespCollectionListResponse';
export type { PageBaseRespFollowResponse } from './models/PageBaseRespFollowResponse';
export type { PageBaseRespFriendReqResponse } from './models/PageBaseRespFriendReqResponse';
export type { PageBaseRespRatingVO } from './models/PageBaseRespRatingVO';
export type { PageBaseRespRepository } from './models/PageBaseRespRepository';
export type { PageBaseRespResourceResponse } from './models/PageBaseRespResourceResponse';
export type { PageBaseRespRoleAbility } from './models/PageBaseRespRoleAbility';
export type { PageBaseRespRuleResponse } from './models/PageBaseRespRuleResponse';
export type { PageBaseRespUserRole } from './models/PageBaseRespUserRole';
export type { PagePostRequest } from './models/PagePostRequest';
export type { PlayerGrantRequest } from './models/PlayerGrantRequest';
export type { PlayerRevokeRequest } from './models/PlayerRevokeRequest';
export type { PostCreateRequest } from './models/PostCreateRequest';
export type { PostListResponse } from './models/PostListResponse';
export type { PostListWithStatsResponse } from './models/PostListWithStatsResponse';
export type { PostResponse } from './models/PostResponse';
export type { PostStatsResponse } from './models/PostStatsResponse';
export type { PostWithStatsResponse } from './models/PostWithStatsResponse';
export type { RatingPageRequest } from './models/RatingPageRequest';
export type { RatingRequest } from './models/RatingRequest';
export type { RatingVO } from './models/RatingVO';
export type { Repository } from './models/Repository';
export type { RepositoryForkPageRequest } from './models/RepositoryForkPageRequest';
export type { RepositoryPageByUserRequest } from './models/RepositoryPageByUserRequest';
export type { RepositoryPageRequest } from './models/RepositoryPageRequest';
export type { RepositoryUpdateRequest } from './models/RepositoryUpdateRequest';
export type { ResourceBatchAddToCollectionRequest } from './models/ResourceBatchAddToCollectionRequest';
export type { ResourceCollectionCreateRequest } from './models/ResourceCollectionCreateRequest';
export type { ResourcePageRequest } from './models/ResourcePageRequest';
export type { ResourceResponse } from './models/ResourceResponse';
export type { ResourceUpdateRequest } from './models/ResourceUpdateRequest';
export type { ResourceUploadRequest } from './models/ResourceUploadRequest';
export type { RoleAbility } from './models/RoleAbility';
export type { RoleAvatar } from './models/RoleAvatar';
export type { RoleAvatarCreateRequest } from './models/RoleAvatarCreateRequest';
export type { RoleCreateRequest } from './models/RoleCreateRequest';
export type { RolePageQueryRequest } from './models/RolePageQueryRequest';
export type { RoleUpdateRequest } from './models/RoleUpdateRequest';
export type { Room } from './models/Room';
export type { RoomAddRequest } from './models/RoomAddRequest';
export type { RoomArchiveCloneRequest } from './models/RoomArchiveCloneRequest';
export type { RoomArchiveRequest } from './models/RoomArchiveRequest';
export type { RoomDndMapClearRequest } from './models/RoomDndMapClearRequest';
export type { RoomDndMapResponse } from './models/RoomDndMapResponse';
export type { RoomDndMapTokenRemoveRequest } from './models/RoomDndMapTokenRemoveRequest';
export type { RoomDndMapTokenResponse } from './models/RoomDndMapTokenResponse';
export type { RoomDndMapTokenUpsertRequest } from './models/RoomDndMapTokenUpsertRequest';
export type { RoomDndMapUpsertRequest } from './models/RoomDndMapUpsertRequest';
export type { RoomExtraRequest } from './models/RoomExtraRequest';
export type { RoomExtraSetRequest } from './models/RoomExtraSetRequest';
export type { RoomListResponse } from './models/RoomListResponse';
export type { RoomMember } from './models/RoomMember';
export type { RoomMemberAddRequest } from './models/RoomMemberAddRequest';
export type { RoomMemberDeleteRequest } from './models/RoomMemberDeleteRequest';
export type { RoomMuteRequest } from './models/RoomMuteRequest';
export type { RoomRoleAddRequest } from './models/RoomRoleAddRequest';
export type { RoomRoleDeleteRequest } from './models/RoomRoleDeleteRequest';
export type { RoomUpdateRequest } from './models/RoomUpdateRequest';
export type { Rule } from './models/Rule';
export type { RuleCloneRequest } from './models/RuleCloneRequest';
export type { RuleCreateRequest } from './models/RuleCreateRequest';
export type { RulePageRequest } from './models/RulePageRequest';
export type { RuleResponse } from './models/RuleResponse';
export type { RuleUpdateRequest } from './models/RuleUpdateRequest';
export type { SessionReadUpdateRequest } from './models/SessionReadUpdateRequest';
export type { ShortLinkCreateRequest } from './models/ShortLinkCreateRequest';
export type { SoundMessage } from './models/SoundMessage';
export type { Space } from './models/Space';
export type { SpaceAddRequest } from './models/SpaceAddRequest';
export type { SpaceArchiveRequest } from './models/SpaceArchiveRequest';
export type { SpaceCloneRequest } from './models/SpaceCloneRequest';
export type { SpaceDocCreateRequest } from './models/SpaceDocCreateRequest';
export type { SpaceDocRenameRequest } from './models/SpaceDocRenameRequest';
export type { SpaceDocResponse } from './models/SpaceDocResponse';
export type { SpaceExtraRequest } from './models/SpaceExtraRequest';
export type { SpaceExtraSetRequest } from './models/SpaceExtraSetRequest';
export type { SpaceMember } from './models/SpaceMember';
export type { SpaceMemberAddRequest } from './models/SpaceMemberAddRequest';
export type { SpaceMemberDeleteRequest } from './models/SpaceMemberDeleteRequest';
export type { SpaceOwnerTransferRequest } from './models/SpaceOwnerTransferRequest';
export type { SpaceRole } from './models/SpaceRole';
export type { SpaceSidebarTreeResponse } from './models/SpaceSidebarTreeResponse';
export type { SpaceSidebarTreeSetRequest } from './models/SpaceSidebarTreeSetRequest';
export type { SpaceUpdateRequest } from './models/SpaceUpdateRequest';
export type { SpaceUserDocCreateRequest } from './models/SpaceUserDocCreateRequest';
export type { SpaceUserDocRenameRequest } from './models/SpaceUserDocRenameRequest';
export type { SpaceUserDocResponse } from './models/SpaceUserDocResponse';
export type { SpaceUserDocTagUpdateRequest } from './models/SpaceUserDocTagUpdateRequest';
export type { Sticker } from './models/Sticker';
export type { StickerCreateRequest } from './models/StickerCreateRequest';
export type { Tag } from './models/Tag';
export type { TagAddRequest } from './models/TagAddRequest';
export type { TagDeleteRequest } from './models/TagDeleteRequest';
export type { TagGetRequest } from './models/TagGetRequest';
export type { TagUpdateRequest } from './models/TagUpdateRequest';
export type { TagUsageRequest } from './models/TagUsageRequest';
export type { UploadUrlRequest } from './models/UploadUrlRequest';
export type { Usage } from './models/Usage';
export type { UserInfo } from './models/UserInfo';
export type { UserInfoResponse } from './models/UserInfoResponse';
export type { UserLoginRequest } from './models/UserLoginRequest';
export type { UserPrivateInfoResponse } from './models/UserPrivateInfoResponse';
export type { UserProfileInfoResponse } from './models/UserProfileInfoResponse';
export type { UserRegisterRequest } from './models/UserRegisterRequest';
export type { UserRole } from './models/UserRole';
export type { UserUpdateInfoRequest } from './models/UserUpdateInfoRequest';
export type { UVOperationDTO } from './models/UVOperationDTO';
export type { WebgalChooseOption } from './models/WebgalChooseOption';
export type { WebgalChoosePayload } from './models/WebgalChoosePayload';
export type { WebgalVarPayload } from './models/WebgalVarPayload';

export { AbilityControllerService } from './services/AbilityControllerService';
export { AiGatewayControllerService } from './services/AiGatewayControllerService';
export { AiGatewayOpenAiControllerService } from './services/AiGatewayOpenAiControllerService';
export { AvatarControllerService } from './services/AvatarControllerService';
export { BlocksuiteDocControllerService } from './services/BlocksuiteDocControllerService';
export { ChatControllerService } from './services/ChatControllerService';
export { ClassificationControllerService } from './services/ClassificationControllerService';
export { CollectionControllerService } from './services/CollectionControllerService';
export { CollectionListControllerService } from './services/CollectionListControllerService';
export { CollectionListItemControllerService } from './services/CollectionListItemControllerService';
export { CommentControllerService } from './services/CommentControllerService';
export { CommunityService } from './services/CommunityService';
export { CommunityPostControllerService } from './services/CommunityPostControllerService';
export { CounterService } from './services/CounterService';
export { DatabaseBackupService } from './services/DatabaseBackupService';
export { FeedControllerService } from './services/FeedControllerService';
export { FriendControllerService } from './services/FriendControllerService';
export { MarkControllerService } from './services/MarkControllerService';
export { MessageDirectControllerService } from './services/MessageDirectControllerService';
export { MessageSessionService } from './services/MessageSessionService';
export { OssControllerService } from './services/OssControllerService';
export { RatingService } from './services/RatingService';
export { RepositoryControllerService } from './services/RepositoryControllerService';
export { ResourceControllerService } from './services/ResourceControllerService';
export { RoleControllerService } from './services/RoleControllerService';
export { RoomControllerService } from './services/RoomControllerService';
export { RoomDndMapControllerService } from './services/RoomDndMapControllerService';
export { RoomMemberControllerService } from './services/RoomMemberControllerService';
export { RoomRoleControllerService } from './services/RoomRoleControllerService';
export { RuleControllerService } from './services/RuleControllerService';
export { ShortLinkControllerService } from './services/ShortLinkControllerService';
export { SpaceControllerService } from './services/SpaceControllerService';
export { SpaceDocControllerService } from './services/SpaceDocControllerService';
export { SpaceMemberControllerService } from './services/SpaceMemberControllerService';
export { SpaceRepositoryControllerService } from './services/SpaceRepositoryControllerService';
export { SpaceSidebarTreeControllerService } from './services/SpaceSidebarTreeControllerService';
export { SpaceUserDocControllerService } from './services/SpaceUserDocControllerService';
export { StickerControllerService } from './services/StickerControllerService';
export { TagControllerService } from './services/TagControllerService';
export { UserControllerService } from './services/UserControllerService';
export { UserFollowControllerService } from './services/UserFollowControllerService';
export { WebsocketDocService } from './services/WebsocketDocService';
