/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { TuanChat } from './TuanChat';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AbilityFieldUpdateRequest } from './models/AbilityFieldUpdateRequest';
export type { AbilityPageRequest } from './models/AbilityPageRequest';
export type { AbilitySetRequest } from './models/AbilitySetRequest';
export type { AbilityUpdateRequest } from './models/AbilityUpdateRequest';
export type { ApiResult } from './models/ApiResult';
export type { ApiResultBoolean } from './models/ApiResultBoolean';
export type { ApiResultCursorPageBaseResponseChatMessageResponse } from './models/ApiResultCursorPageBaseResponseChatMessageResponse';
export type { ApiResultCursorPageBaseResponseFeed } from './models/ApiResultCursorPageBaseResponseFeed';
export type { ApiResultFeed } from './models/ApiResultFeed';
export type { ApiResultListChatMessageResponse } from './models/ApiResultListChatMessageResponse';
export type { ApiResultListLikeStatusResp } from './models/ApiResultListLikeStatusResp';
export type { ApiResultListRoleAbility } from './models/ApiResultListRoleAbility';
export type { ApiResultListRoleAvatar } from './models/ApiResultListRoleAvatar';
export type { ApiResultListRoleResponse } from './models/ApiResultListRoleResponse';
export type { ApiResultListRoom } from './models/ApiResultListRoom';
export type { ApiResultListRoomMember } from './models/ApiResultListRoomMember';
export type { ApiResultListRule } from './models/ApiResultListRule';
export type { ApiResultListSpace } from './models/ApiResultListSpace';
export type { ApiResultListSpaceMember } from './models/ApiResultListSpaceMember';
export type { ApiResultListUserRole } from './models/ApiResultListUserRole';
export type { ApiResultLong } from './models/ApiResultLong';
export type { ApiResultMapObjectObject } from './models/ApiResultMapObjectObject';
export type { ApiResultMessage } from './models/ApiResultMessage';
export type { ApiResultObject } from './models/ApiResultObject';
export type { ApiResultOssResp } from './models/ApiResultOssResp';
export type { ApiResultPageBaseRespLikeRecord } from './models/ApiResultPageBaseRespLikeRecord';
export type { ApiResultPageBaseRespRoleAbility } from './models/ApiResultPageBaseRespRoleAbility';
export type { ApiResultPageBaseRespRoleResponse } from './models/ApiResultPageBaseRespRoleResponse';
export type { ApiResultPageBaseRespRule } from './models/ApiResultPageBaseRespRule';
export type { ApiResultRoleAbility } from './models/ApiResultRoleAbility';
export type { ApiResultRoleAvatar } from './models/ApiResultRoleAvatar';
export type { ApiResultRoleResponse } from './models/ApiResultRoleResponse';
export type { ApiResultRoom } from './models/ApiResultRoom';
export type { ApiResultRule } from './models/ApiResultRule';
export type { ApiResultSpace } from './models/ApiResultSpace';
export type { ApiResultString } from './models/ApiResultString';
export type { ApiResultUserInfoResponse } from './models/ApiResultUserInfoResponse';
export type { ApiResultVoid } from './models/ApiResultVoid';
export type { BatchLikeRecordRequest } from './models/BatchLikeRecordRequest';
export type { ChatMessagePageRequest } from './models/ChatMessagePageRequest';
export type { ChatMessageRequest } from './models/ChatMessageRequest';
export type { ChatMessageResponse } from './models/ChatMessageResponse';
export type { CursorPageBaseResponseChatMessageResponse } from './models/CursorPageBaseResponseChatMessageResponse';
export type { CursorPageBaseResponseFeed } from './models/CursorPageBaseResponseFeed';
export type { DiceResult } from './models/DiceResult';
export type { Feed } from './models/Feed';
export type { FeedPageRequest } from './models/FeedPageRequest';
export type { FeedRequest } from './models/FeedRequest';
export type { FileMessage } from './models/FileMessage';
export type { ForwardMessage } from './models/ForwardMessage';
export type { ImageMessage } from './models/ImageMessage';
export { ImageToImageRequest } from './models/ImageToImageRequest';
export type { LikeRecord } from './models/LikeRecord';
export type { LikeRecordRequest } from './models/LikeRecordRequest';
export type { LikeStatusResp } from './models/LikeStatusResp';
export type { LikeTarget } from './models/LikeTarget';
export type { Message } from './models/Message';
export type { MessageExtra } from './models/MessageExtra';
export type { MessageMark } from './models/MessageMark';
export type { MoveMessageRequest } from './models/MoveMessageRequest';
export type { OssResp } from './models/OssResp';
export type { PageBaseRequest } from './models/PageBaseRequest';
export type { PageBaseRespLikeRecord } from './models/PageBaseRespLikeRecord';
export type { PageBaseRespRoleAbility } from './models/PageBaseRespRoleAbility';
export type { PageBaseRespRoleResponse } from './models/PageBaseRespRoleResponse';
export type { PageBaseRespRule } from './models/PageBaseRespRule';
export type { PlayerGrantRequest } from './models/PlayerGrantRequest';
export type { PlayerRevokeRequest } from './models/PlayerRevokeRequest';
export type { RoleAbility } from './models/RoleAbility';
export type { RoleAvatar } from './models/RoleAvatar';
export type { RoleAvatarCreateRequest } from './models/RoleAvatarCreateRequest';
export type { RoleCreateRequest } from './models/RoleCreateRequest';
export type { RoleGenerationRequest } from './models/RoleGenerationRequest';
export type { RolePageQueryRequest } from './models/RolePageQueryRequest';
export type { RoleResponse } from './models/RoleResponse';
export type { RoleUpdateRequest } from './models/RoleUpdateRequest';
export type { Room } from './models/Room';
export type { RoomAddRequest } from './models/RoomAddRequest';
export type { RoomMember } from './models/RoomMember';
export type { RoomMemberAddRequest } from './models/RoomMemberAddRequest';
export type { RoomMemberDeleteRequest } from './models/RoomMemberDeleteRequest';
export type { RoomRoleAddRequest } from './models/RoomRoleAddRequest';
export type { RoomRoleDeleteRequest } from './models/RoomRoleDeleteRequest';
export type { RoomUpdateRequest } from './models/RoomUpdateRequest';
export type { Rule } from './models/Rule';
export type { RuleCloneRequest } from './models/RuleCloneRequest';
export type { RuleCreateRequest } from './models/RuleCreateRequest';
export type { RulePageRequest } from './models/RulePageRequest';
export type { RuleUpdateRequest } from './models/RuleUpdateRequest';
export type { SimpleTTSRequest } from './models/SimpleTTSRequest';
export type { Space } from './models/Space';
export type { SpaceAddRequest } from './models/SpaceAddRequest';
export type { SpaceArchiveRequest } from './models/SpaceArchiveRequest';
export type { SpaceMember } from './models/SpaceMember';
export type { SpaceMemberAddRequest } from './models/SpaceMemberAddRequest';
export type { SpaceMemberDeleteRequest } from './models/SpaceMemberDeleteRequest';
export type { SpaceOwnerTransferRequest } from './models/SpaceOwnerTransferRequest';
export type { SpaceRoleAddRequest } from './models/SpaceRoleAddRequest';
export type { SpaceRoleDeleteRequest } from './models/SpaceRoleDeleteRequest';
export type { SpaceUpdateRequest } from './models/SpaceUpdateRequest';
export type { TextToImageRequest } from './models/TextToImageRequest';
export type { TTSResponse } from './models/TTSResponse';
export type { UploadUrlRequest } from './models/UploadUrlRequest';
export type { UserInfoResponse } from './models/UserInfoResponse';
export type { UserLoginRequest } from './models/UserLoginRequest';
export type { UserRegisterRequest } from './models/UserRegisterRequest';
export type { UserRole } from './models/UserRole';

export { Service } from './services/Service';
export { AbilityControllerService } from './services/AbilityControllerService';
export { AvatarControllerService } from './services/AvatarControllerService';
export { ChatControllerService } from './services/ChatControllerService';
export { DiceCommentControllerService } from './services/DiceCommentControllerService';
export { FeedControllerService } from './services/FeedControllerService';
export { ImageGenerationControllerService } from './services/ImageGenerationControllerService';
export { OssControllerService } from './services/OssControllerService';
export { RoleControllerService } from './services/RoleControllerService';
export { RoleGenerationControllerService } from './services/RoleGenerationControllerService';
export { RoomControllerService } from './services/RoomControllerService';
export { RoomMemberControllerService } from './services/RoomMemberControllerService';
export { RoomRoleControllerService } from './services/RoomRoleControllerService';
export { RuleControllerService } from './services/RuleControllerService';
export { SpaceControllerService } from './services/SpaceControllerService';
export { SpaceMemberControllerService } from './services/SpaceMemberControllerService';
export { SpaceRoleControllerService } from './services/SpaceRoleControllerService';
export { TtsControllerService } from './services/TtsControllerService';
export { UserControllerService } from './services/UserControllerService';
